"""Immutable adapter archives: structural/integrity checks, never code execution.

The API copy is generated by scripts/sync-instrument-contract.mjs. Runtime schema
semantics, source trust, installation permission and hardware qualification are
separate gates; a structurally valid archive is not safe or approved software.
"""

from __future__ import annotations

import base64
import configparser
import csv
import hashlib
import io
import json
import re
import stat
import zipfile
from email.parser import BytesParser
from typing import Any

MAX_ARCHIVE_BYTES = 64 * 1024 * 1024
MAX_EXPANDED_BYTES = 256 * 1024 * 1024
MAX_FILES = 4096
SEMVER = re.compile(
    r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$"
)
IDENTIFIER = re.compile(r"^[a-z][a-z0-9_.-]{1,127}$")
DIGEST = re.compile(r"^[a-f0-9]{64}$")
ENTRY_POINT = re.compile(r"^[a-zA-Z_]\w*(?:\.[a-zA-Z_]\w*)*:[a-zA-Z_]\w*$")


def sha256(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def canonical(value: Any) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        ensure_ascii=False,
        separators=(",", ":"),
        allow_nan=False,
    ).encode()


def _object(value, keys, label):
    if not isinstance(value, dict) or set(value) != set(keys):
        raise ValueError(f"{label} requires exactly: {', '.join(keys)}")
    return value


def _text(value, label, limit=4000):
    if (
        not isinstance(value, str)
        or not value.strip()
        or len(value) > limit
        or any(ord(c) < 32 for c in value)
    ):
        raise ValueError(f"Invalid {label}")
    return value


def _list(value, label, limit=64, *, empty=False):
    if not isinstance(value, list) or len(value) > limit or (not value and not empty):
        raise ValueError(f"Invalid {label}")
    return value


def safe_path(value: str) -> str:
    _text(value, "archive path", 240)
    if value.startswith("/") or "\\" in value or ":" in value:
        raise ValueError("Archive paths must be relative portable paths")
    for part in value.split("/"):
        if (
            not re.fullmatch(r"[A-Za-z0-9_][A-Za-z0-9_.-]*", part)
            or part.endswith((".", " "))
            or part.split(".")[0].upper()
            in {
                "CON",
                "PRN",
                "AUX",
                "NUL",
                *[f"{kind}{i}" for kind in ("COM", "LPT") for i in range(1, 10)],
            }
        ):
            raise ValueError("Unsafe archive path")
    return value


def strict_json(raw: bytes):
    def pairs(items):
        result = {}
        for key, value in items:
            if key in result:
                raise ValueError("Duplicate JSON key")
            result[key] = value
        return result

    def constant(_value):
        raise ValueError("Non-finite JSON value")

    try:
        return json.loads(raw, object_pairs_hook=pairs, parse_constant=constant)
    except (RecursionError, UnicodeDecodeError) as error:
        raise ValueError("Invalid or deeply nested JSON") from error


def _zip_files(raw: bytes, *, max_bytes=MAX_EXPANDED_BYTES) -> dict[str, bytes]:
    if not isinstance(raw, bytes) or len(raw) > MAX_ARCHIVE_BYTES:
        raise ValueError("Archive exceeds compressed size limit")
    result = {}
    seen = set()
    try:
        with zipfile.ZipFile(io.BytesIO(raw)) as archive:
            entries = archive.infolist()
            if (
                len(entries) > MAX_FILES
                or sum(entry.file_size for entry in entries) > max_bytes
            ):
                raise ValueError("Archive exceeds expanded limits")
            for entry in entries:
                path = safe_path(entry.filename.rstrip("/"))
                if path.casefold() in seen:
                    raise ValueError("Duplicate or case-colliding archive path")
                seen.add(path.casefold())
                mode = entry.external_attr >> 16
                file_type = stat.S_IFMT(mode)
                if entry.flag_bits & 1 or file_type not in {
                    0,
                    stat.S_IFREG,
                    stat.S_IFDIR,
                }:
                    raise ValueError(
                        "Encrypted archives and special files are not supported"
                    )
                if entry.is_dir():
                    continue
                # Check advertised limits before decompression, then actual bytes/CRC.
                value = archive.read(entry)
                if len(value) != entry.file_size:
                    raise ValueError("Archive member size changed")
                result[path] = value
            folded_files = {name.casefold() for name in result}
            for path in result:
                parts = path.casefold().split("/")
                if any(
                    "/".join(parts[:index]) in folded_files
                    for index in range(1, len(parts))
                ):
                    raise ValueError("Archive file conflicts with a parent directory")
    except (zipfile.BadZipFile, NotImplementedError, RuntimeError) as error:
        raise ValueError("Invalid or unsupported ZIP archive") from error
    return result


def _distribution_name(name):
    return re.sub(r"[-_.]+", "-", _text(name, "distribution name", 128)).lower()


def wheel_identity(raw: bytes) -> dict:
    files = _zip_files(raw)
    metadata = [name for name in files if name.endswith(".dist-info/METADATA")]
    if len(metadata) != 1:
        raise ValueError("Wheel must have exactly one distribution metadata file")
    prefix = metadata[0].removesuffix("METADATA")
    if prefix + "WHEEL" not in files or prefix + "RECORD" not in files:
        raise ValueError("Wheel metadata is incomplete")
    if any(".dist-info/" in name and not name.startswith(prefix) for name in files):
        raise ValueError("Wheel contains foreign distribution metadata")
    wheel_fields = BytesParser().parsebytes(files[prefix + "WHEEL"])
    if wheel_fields.get("Wheel-Version") != "1.0":
        raise ValueError("Unsupported wheel format")
    recorded = set()
    for record in csv.reader(io.StringIO(files[prefix + "RECORD"].decode())):
        if len(record) != 3 or record[0] in recorded or record[0] not in files:
            raise ValueError("Invalid wheel RECORD")
        name, checksum, size = record
        recorded.add(name)
        if name == prefix + "RECORD":
            if checksum or size:
                raise ValueError("Wheel RECORD must not hash itself")
            continue
        expected = "sha256=" + base64.urlsafe_b64encode(
            hashlib.sha256(files[name]).digest()
        ).decode().rstrip("=")
        if checksum != expected or size != str(len(files[name])):
            raise ValueError("Wheel RECORD integrity mismatch")
    if recorded != set(files):
        raise ValueError("Wheel RECORD must cover every file")
    if any(
        name.endswith(".pth")
        or name.split("/")[0] in {"sitecustomize.py", "usercustomize.py"}
        or ".data/" in name
        for name in files
    ):
        raise ValueError(
            "Wheel startup hooks and relocated data/scripts require a separate installer"
        )
    fields = BytesParser().parsebytes(files[metadata[0]])
    if len(fields.get_all("Name", [])) != 1 or len(fields.get_all("Version", [])) != 1:
        raise ValueError("Wheel distribution identity is ambiguous")
    points = {}
    if prefix + "entry_points.txt" in files:
        parser = configparser.ConfigParser(interpolation=None)
        parser.read_string(files[prefix + "entry_points.txt"].decode())
        if parser.has_section("airalogy.instrument_adapters"):
            points = dict(parser.items("airalogy.instrument_adapters"))
            if any(
                not IDENTIFIER.fullmatch(name) or not ENTRY_POINT.fullmatch(target)
                for name, target in points.items()
            ):
                raise ValueError("Invalid adapter entry point")
    return {
        "name": _distribution_name(fields["Name"]),
        "version": _text(fields["Version"], "wheel version", 128),
        "entry_points": points,
        "requirements": fields.get_all("Requires-Dist", []),
        "paths": sorted(files),
        "expanded_bytes": sum(map(len, files.values())),
    }


def _validate_manifest(value: dict) -> dict:
    _object(
        value,
        [
            "schema",
            "id",
            "version",
            "entry_point",
            "provenance",
            "compatibility",
            "commands",
            "files",
            "limitations",
        ],
        "Manifest",
    )
    if value["schema"] != "airalogy.adapter-package.v1":
        raise ValueError("Unsupported adapter package schema")
    if not IDENTIFIER.fullmatch(
        _text(value["id"], "package id", 128)
    ) or not SEMVER.fullmatch(_text(value["version"], "package version", 64)):
        raise ValueError("Package requires a stable id and SemVer version")
    if not IDENTIFIER.fullmatch(_text(value["entry_point"], "entry point", 128)):
        raise ValueError("Invalid entry point name")
    provenance = _object(
        value["provenance"],
        ["author", "kind", "license", "build_reference", "sources"],
        "Provenance",
    )
    for field in ["author", "license", "build_reference"]:
        _text(provenance[field], field)
    if provenance["kind"] not in {"manual", "aira"}:
        raise ValueError("Invalid source kind")
    for source in _list(provenance["sources"], "source references", empty=True):
        _text(source, "source reference")
    compatibility = _object(
        value["compatibility"],
        ["gateway_versions", "python_versions", "declared", "tested"],
        "Compatibility",
    )
    for version in _list(compatibility["gateway_versions"], "Gateway versions", 16):
        if not SEMVER.fullmatch(_text(version, "Gateway version", 64)):
            raise ValueError("Gateway versions must be exact")
    for version in _list(compatibility["python_versions"], "Python versions", 16):
        if not re.fullmatch(r"3\.\d{1,2}", _text(version, "Python version", 5)):
            raise ValueError("Python compatibility uses exact major.minor versions")
    for combination in _list(compatibility["declared"], "declared compatibility", 32):
        _object(
            combination,
            [
                "manufacturer",
                "model",
                "firmware",
                "application",
                "application_version",
                "os",
                "architecture",
            ],
            "Compatibility combination",
        )
        for field, text in combination.items():
            _text(text, field, 256)
    for tested in _list(compatibility["tested"], "test declarations", 64, empty=True):
        _object(
            tested,
            ["combination_index", "reference", "simulation_only"],
            "Test declaration",
        )
        if (
            type(tested["combination_index"]) is not int
            or not 0 <= tested["combination_index"] < len(compatibility["declared"])
            or type(tested["simulation_only"]) is not bool
        ):
            raise ValueError("Invalid tested combination")
        _text(tested["reference"], "test reference")
    commands = _list(value["commands"], "commands", 32)
    identities = set()
    for command in commands:
        _object(
            command,
            [
                "key",
                "version",
                "name",
                "input_schema",
                "output_schema",
                "risk",
                "device_confirmation_required",
                "safety_contract",
                "timeout_seconds",
                "units",
                "effects",
                "completion",
                "stop",
                "retry",
                "outputs",
            ],
            "Command",
        )
        identity = (
            _text(command["key"], "command key", 128),
            _text(command["version"], "command version", 64),
        )
        if not IDENTIFIER.fullmatch(identity[0]) or identity in identities:
            raise ValueError("Invalid or repeated command identity")
        identities.add(identity)
        for field in ["name", "completion", "stop"]:
            _text(command[field], field)
        for field in ["input_schema", "output_schema"]:
            if (
                not isinstance(command[field], dict)
                or command[field].get("type") != "object"
                or len(canonical(command[field])) > 64 * 1024
            ):
                raise ValueError("Command schemas must be bounded JSON objects")
        if (
            command["risk"] not in {"read_only", "low", "medium", "high"}
            or type(command["device_confirmation_required"]) is not bool
        ):
            raise ValueError("Invalid command risk/confirmation")
        if (
            command["risk"] in {"medium", "high"}
            and not command["device_confirmation_required"]
        ):
            raise ValueError("Medium/high risk commands require local confirmation")
        safety = _object(
            command["safety_contract"],
            [
                "required_interlocks",
                "operator_presence_required",
                "emergency_stop_required",
            ],
            "Safety contract",
        )
        for interlock in _list(
            safety["required_interlocks"], "interlocks", 32, empty=True
        ):
            if not IDENTIFIER.fullmatch(_text(interlock, "interlock", 128)):
                raise ValueError("Invalid interlock")
        if any(
            type(safety[key]) is not bool
            for key in ["operator_presence_required", "emergency_stop_required"]
        ):
            raise ValueError("Safety flags must be booleans")
        if command["risk"] == "high" and not (
            safety["operator_presence_required"] and safety["emergency_stop_required"]
        ):
            raise ValueError("High risk commands require operator and emergency stop")
        if (
            type(command["timeout_seconds"]) is not int
            or not 1 <= command["timeout_seconds"] <= 86400
            or command["retry"] != "never"
        ):
            raise ValueError(
                "Commands require bounded time and no automatic physical retry"
            )
        for field in ["effects", "units"]:
            for text in _list(command[field], field, 64, empty=field == "units"):
                _text(text, field, 512)
        names = set()
        for output in _list(command["outputs"], "output files", 16, empty=True):
            _object(
                output, ["name", "media_type", "max_bytes", "required"], "Output file"
            )
            name = safe_path(output["name"])
            if (
                "/" in name
                or name in names
                or type(output["max_bytes"]) is not int
                or not 1 <= output["max_bytes"] <= 2_147_483_647
                or type(output["required"]) is not bool
            ):
                raise ValueError("Invalid output file contract")
            names.add(name)
            if not re.fullmatch(
                r"[\w.+-]+/[\w.+-]+", _text(output["media_type"], "media type", 128)
            ):
                raise ValueError("Invalid media type")
    paths = set()
    for entry in _list(value["files"], "files", 256):
        _object(entry, ["path", "sha256", "size_bytes", "role"], "Package file")
        path = safe_path(entry["path"])
        if path.casefold() in paths or path == "manifest.json":
            raise ValueError("Repeated/reserved file path")
        paths.add(path.casefold())
        if (
            not DIGEST.fullmatch(_text(entry["sha256"], "file digest", 64))
            or type(entry["size_bytes"]) is not int
            or not 0 <= entry["size_bytes"] <= MAX_ARCHIVE_BYTES
        ):
            raise ValueError("Invalid file digest or size")
        if entry["role"] not in {
            "adapter_wheel",
            "dependency_wheel",
            "source",
            "test",
            "license",
        }:
            raise ValueError("Unknown package file role")
        prefix = {
            "adapter_wheel": "wheels/",
            "dependency_wheel": "wheels/",
            "source": "source/",
            "test": "tests/",
            "license": "licenses/",
        }[entry["role"]]
        if not path.startswith(prefix) or (
            entry["role"].endswith("wheel") and not path.endswith(".whl")
        ):
            raise ValueError("File role/path mismatch")
    roles = [entry["role"] for entry in value["files"]]
    if roles.count("adapter_wheel") != 1 or not all(
        role in roles for role in ["source", "test", "license"]
    ):
        raise ValueError(
            "Package requires one adapter wheel, source, tests and license"
        )
    for limitation in _list(value["limitations"], "limitations"):
        _text(limitation, "limitation")
    if len(canonical(value)) > 256 * 1024:
        raise ValueError("Manifest is too large")
    return value


def validate_manifest(value: dict) -> dict:
    try:
        return _validate_manifest(value)
    except (TypeError, KeyError, RecursionError, OverflowError) as error:
        raise ValueError("Malformed adapter manifest") from error


def _inspect_package(raw: bytes) -> dict:
    files = _zip_files(raw)
    if "manifest.json" not in files or len(files["manifest.json"]) > 256 * 1024:
        raise ValueError("Package manifest missing or oversized")
    manifest = validate_manifest(strict_json(files.pop("manifest.json")))
    if set(files) != {entry["path"] for entry in manifest["files"]}:
        raise ValueError("Archive must contain exactly the declared payload files")
    wheels = {}
    wheel_paths = set()
    expanded = 0
    adapter = None
    for entry in manifest["files"]:
        payload = files[entry["path"]]
        if len(payload) != entry["size_bytes"] or sha256(payload) != entry["sha256"]:
            raise ValueError("Package file integrity check failed")
        if entry["role"].endswith("wheel"):
            wheel = wheel_identity(payload)
            expanded += wheel["expanded_bytes"]
            if expanded > MAX_EXPANDED_BYTES:
                raise ValueError("Combined wheel contents exceed expanded limit")
            if (
                wheel["name"] in wheels
                or wheel["name"] == "airalogy-instrument-gateway"
                or any(
                    path.casefold().split("/")[0]
                    in {"airalogy_instrument_gateway", "airalogy_instrument_gateway.py"}
                    for path in wheel["paths"]
                )
            ):
                raise ValueError(
                    "Duplicate dependency or attempted Gateway replacement"
                )
            for path in wheel["paths"]:
                folded = path.casefold()
                if folded in wheel_paths:
                    raise ValueError("Wheel installation paths overlap")
                wheel_paths.add(folded)
            wheels[wheel["name"]] = wheel
            if entry["role"] == "adapter_wheel":
                adapter = wheel
            elif wheel["entry_points"]:
                raise ValueError(
                    "Dependencies cannot register additional adapter entry points"
                )
    if set(adapter["entry_points"]) != {manifest["entry_point"]}:
        raise ValueError("Wheel entry point does not match the manifest")
    return {
        "schema": "airalogy.adapter-inspection.v1",
        "archive_digest": sha256(raw),
        "manifest_digest": sha256(canonical(manifest)),
        "manifest": manifest,
        "wheels": wheels,
        "hardware_authorized": False,
    }


def inspect_package(raw: bytes) -> dict:
    try:
        return _inspect_package(raw)
    except (
        TypeError,
        KeyError,
        RecursionError,
        UnicodeDecodeError,
        csv.Error,
        configparser.Error,
    ) as error:
        raise ValueError("Malformed adapter archive or wheel metadata") from error


def pack(manifest: dict, payloads: dict[str, bytes]) -> bytes:
    """Deterministic ZIP; callers explicitly supply payloads, no referenced files opened."""
    validate_manifest(manifest)
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for name, data in sorted(
            {"manifest.json": canonical(manifest), **payloads}.items()
        ):
            info = zipfile.ZipInfo(safe_path(name), date_time=(1980, 1, 1, 0, 0, 0))
            info.external_attr = (stat.S_IFREG | 0o444) << 16
            info.compress_type = zipfile.ZIP_DEFLATED
            archive.writestr(info, data)
    raw = output.getvalue()
    inspect_package(raw)
    return raw
