// This file is auto-generated by scripts/generate-i18n-types.mjs.
// Do not edit by hand.

declare namespace I18n {
  interface Schema {
    system: {
      title: string
    }
    common: {
      tip: string
      add: string
      addMember: string
      addMembers: string
      addSuccess: string
      edit: string
      editSuccess: string
      delete: string
      deleteSuccess: string
      batchDelete: string
      confirm: string
      cancel: string
      undo: string
      pleaseCheckValue: string
      action: string
      backToHome: string
      lookForward: string
      userCenter: string
      profile: string
      projects: string
      labs: string
      logout: string
      logoutConfirm: string
      login: string
      signup: string
      adminDashboard: string
      hub: string
      chat: string
      docs: string
      docsFull: string
      openDocs: string
      menu: string
      index: string
      selectCountry: string
      next: string
      previous: string
      new: string
      create: string
      save: string
      remove: string
      or: string
      emptyList: string
      loadError: string
      labsLabel: string
      projectsLabel: string
      protocolsLabel: string
      newRecord: string
      newProtocol: string
      newProject: string
      newGroup: string
      newLab: string
      addRecord: string
      selectFile: string
      upload: string
      major: string
      minor: string
      patch: string
      stars: string
      reuses: string
      downloads: string
      records: string
      allVersions: string
      version: string
      versionWithNumber: string
      lastUpdated: string
      license: string
      none: string
      forks: string
      views: string
      actions: string
      confirmDelete: string
      category: string
      sortBy: string
      memberSearchPlaceholder: string
      searchBy: string
      sortedBy: string
      all: string
      created: string
      updated: string
      createdBy: string
      report: string
      from: string
      starsCount: string
      reusesCount: string
      recordsCount: string
      updatedAt: string
      id: string
      idInput: {
        check: string
        placeholder: {
          lab: string
          group: string
          project: string
          protocol: string
          hub: string
          default: string
        }
        tooltip: {
          lab: string
          project: string
          protocol: string
          hub: string
          default: string
        }
      }
      by: string
      star: string
      unstar: string
      reuse: string
      reupload: string
      more: string
      fields: string
      history: string
      me: string
      can: string
      noDescriptionFor: string
      field: string
      type: string
      default: string
      myStarred: string
      newFolder: string
      noFoldersYet: string
      defaultFolder: string
      defaultFolderCannotRename: string
      defaultFolderCannotDelete: string
      description: string
      enum: string
      arrayItems: string
      examples: string
      format: string
      assignerMode: string
      assignerDependencies: string
      airalogyType: string
      uploadAvatar: string
      removeAvatar: string
      accept: string
      status: string
      title: string
      name: string
      avatar: string
      alias: string
      user: string
      role: string
      aliasPlaceholder: string
      fullscreen: string
      reselect: string
      redo: string
      nodeNotFound: string
      var: string
      assigner: string
      rowIndex: string
      addRow: string
      execute: string
      stop: string
      unknownError: string
      file: string
      preview: string
      download: string
      csvPreview: string
      pdfPreview: string
      readOnly: string
      info: string
      modify: string
      submit: string
      close: string
      unknown: string
      unknownLab: string
      unknownProject: string
      createdAt: string
      checkPassed: string
      checkFailed: string
      toBeChecked: string
      true: string
      false: string
      discardTitle: string
      discardWarning: string
      discardConfirm: string
      discardCancel: string
      actionNotImplemented: string
      variables: string
      protocol: string
      record: string
      project: string
      lab: string
      uuid: string
      selectTime: string
      hour: string
      minute: string
      second: string
      stepIndex: string
      noContent: string
      referenceNotFound: string
      value: string
      noValue: string
      loadingImage: string
      loadImageFailed: string
      disciplines: string
      keywords: string
      authors: string
      maintainers: string
      email: string
      airalogyFileId: string
      source: string
      noImageSource: string
      figureIndex: string
      figureIndexWithTitle: string
      pdfNotSupported: string
      downloadPdf: string
      deleteEntityTitle: string
      deleteWarningTitle: string
      deleteWarningBody: string
      deleteAboutTo: string
      typeToConfirm: string
      typeToConfirmPlaceholder: string
      selectNewRole: string
      current: string
      group: string
      memberRemoveFailed: string
      memberRemoveTitle: string
      memberRemoveTitleWithOrg: string
      memberRemoveConfirm: string
      memberRemoveSuccess: string
      setAlias: string
      setUserAlias: string
      labAliasLabel: string
      labAliasPlaceholder: string
      labAliasRequired: string
      userAliasLabel: string
      userAliasPlaceholder: string
      userAliasRequired: string
      changeRole: string
      footer: {
        copyright: string
        partners: string
      }
      my: string
      readMore: string
      showLess: string
    }
    theme: {
      themeSchema: {
        title: string
        light: string
        dark: string
        auto: string
      }
      layoutMode: {
        title: string
        vertical: string
        horizontal: string
        "vertical-mix": string
        "horizontal-mix": string
      }
      themeColor: {
        title: string
        primary: string
        info: string
        success: string
        warning: string
        error: string
        followPrimary: string
      }
      scrollMode: {
        title: string
        wrapper: string
        content: string
      }
      page: {
        animate: string
        mode: {
          title: string
          fade: string
          "fade-slide": string
          "fade-bottom": string
          "fade-scale": string
          "zoom-fade": string
          "zoom-out": string
          none: string
        }
      }
      fixedHeaderAndTab: string
      header: {
        height: string
        breadcrumb: {
          visible: string
          showIcon: string
        }
      }
      tab: {
        visible: string
        cache: string
        height: string
        mode: {
          title: string
          chrome: string
          button: string
        }
      }
      sider: {
        inverted: string
        width: string
        collapsedWidth: string
        mixWidth: string
        mixCollapsedWidth: string
        mixChildMenuWidth: string
      }
      footer: {
        visible: string
        fixed: string
        height: string
        right: string
      }
      themeDrawerTitle: string
      pageFunTitle: string
      configOperation: {
        copyConfig: string
        copySuccessMsg: string
        resetConfig: string
        resetSuccessMsg: string
      }
    }
    route: {
      "403": string
      "404": string
      "500": string
      "lab-groups": string
      "lab-members": string
      "lab-projects": string
      "labs-my": string
      "labs-public": string
      login: string
      home: string
      "user-center": string
      about: string
      function: string
      function_tab: string
      "function_multi-tab": string
      manage: string
      manage_user: string
      "manage_user-detail": string
      manage_role: string
      manage_route: string
      exception: string
      exception_403: string
      exception_404: string
      exception_500: string
      activity: string
      groups: string
      labs: string
      log: string
      projects: string
      protocol: string
      user: string
      profile: string
    }
    page: {
      auth: {
        heroTitle: string
      }
      login: {
        common: {
          loginOrRegister: string
          usernamePlaceholder: string
          displayNamePlaceholder: string
          phonePlaceholder: string
          emailPlaceholder: string
          codePlaceholder: string
          passwordPlaceholder: string
          newPasswordPlaceholder: string
          confirmPasswordPlaceholder: string
          codeLogin: string
          confirm: string
          back: string
          continue: string
          validateSuccess: string
          loginSuccess: string
          signupSuccess: string
          welcomeBack: string
          welcome: string
          resend: string
          sendCode: string
          resendCooldown: string
          sendCodeSuccess: string
          sendCodeFailure: string
          didntReceiveCode: string
          changePhoneNumber: string
          sendingCode: string
          noAccount: string
          alreadyHaveAccount: string
          verify: string
        }
        emailLogin: {
          title: string
          heading: string
          helper: string
          rememberMe: string
          forgetPassword: string
          register: string
          otherAccountLogin: string
          otherLoginMode: string
          superAdmin: string
          admin: string
          user: string
          confirm: string
        }
        devQuick: {
          title: string
          description: string
          owner: string
          collaborator: string
          viewer: string
          hint: string
          missingAccount: string
          protocolExamplesUnavailable: string
        }
        codeLogin: {
          title: string
          heading: string
          helper: string
          verificationTitle: string
          codeSentTo: string
          noAccountTitle: string
          noAccountContent: string
          sendFailed: string
          resendFailed: string
          notAvailable: string
          getCode: string
          imageCodePlaceholder: string
          confirm: string
        }
        register: {
          title: string
          createAccountTitle: string
          createAccountHelper: string
          profileTitle: string
          profileHelper: string
          displayNameHint: string
          usernameHint: string
          displayNameHintShort: string
          usernameHintShort: string
          agreement: string
          protocol: string
          policy: string
          confirm: string
        }
        login: {
          title: string
        }
        resetPwd: {
          title: string
          helper: string
        }
        phoneSignUp: {
          step1: string
          step2: string
          step3: string
          finalStep: string
          jumpToStep: string
          confirmButton: string
          step1Label: string
          step2Label: string
          success: string
          failure: string
        }
        verifyPhone: {
          title: string
          helper: string
          permanentHint: string
          verificationTitle: string
          codeSentTo: string
          enterCodeLabel: string
          sendFailed: string
          verifyFailed: string
          resendFailed: string
          codeIncomplete: string
          codeInvalid: string
        }
        testingNotice: {
          title: string
          successTitle: string
          message: string
          helper: string
          exploreLater: string
          getStarted: string
        }
        formOverlay: {
          title: string
          description: string
          button: string
        }
        bindWeChat: {
          title: string
        }
      }
      about: {
        title: string
        introduction: string
        projectInfo: {
          title: string
          version: string
          latestBuildTime: string
          githubLink: string
          previewLink: string
        }
        prdDep: string
        devDep: string
      }
      home: {
        dashboardTitle: string
        projectCount: string
        todo: string
        message: string
        schedule: string
        projectNews: {
          title: string
          moreNews: string
          desc1: string
          desc2: string
          desc3: string
          desc4: string
          desc5: string
        }
        labs: string
        projects: string
        pinned: string
        pinnedManage: string
        pinnedManageTitle: string
        pinnedSearchLabsPlaceholder: string
        pinnedSearchProjectsPlaceholder: string
        pinnedSearchProtocolsPlaceholder: string
        pinnedLimitHint: string
        pinnedLimitReached: string
        pinnedTabLabs: string
        pinnedTabProjects: string
        pinnedTabProtocols: string
        pinnedEmptyResults: string
        pinnedProjects: string
        pinnedLabMeta: string
        pinnedMembers: string
        pinnedReorderHint: string
        pinnedEmptyTitle: string
        pinnedEmptyDesc: string
        start: {
          eyebrow: string
          title: string
          description: string
          primaryAction: string
          hubAction: string
          steps: {
            workspace: {
              title: string
              description: string
            }
            protocol: {
              title: string
              description: string
            }
            record: {
              title: string
              description: string
            }
          }
        }
        empty: {
          title: string
          description: string
          createLabAction: string
          hubAction: string
        }
        activities: string
        loadMore: string
        recentProtocols: string
        placeholder: string
        activityAction: {
          added: string
          created: string
          updated: string
          deleted: string
          joined: string
          left: string
        }
        activityText: {
          project: string
          lab: string
          record: string
          protocol: string
          group: string
        }
      }
      recordDiary: {
        tab: string
        empty: string
        recordTitle: string
        recordFallback: string
        version: string
        viewReport: string
        filterAllAccessible: string
        filterMySubmissions: string
        filterAllLabs: string
        labFilterPlaceholder: string
        filterAllProjects: string
        projectFilterPlaceholder: string
        heatmapTitle: string
        heatmapHint: string
        calendarTitle: string
        calendarHint: string
        calendarTruncated: string
        calendarToday: string
        calendarMonth: string
        selectedDate: string
      }
      function: {
        tab: {
          tabOperate: {
            title: string
            addTab: string
            addTabDesc: string
            closeTab: string
            closeCurrentTab: string
            closeAboutTab: string
            addMultiTab: string
            addMultiTabDesc1: string
            addMultiTabDesc2: string
          }
          tabTitle: {
            title: string
            changeTitle: string
            change: string
            resetTitle: string
            reset: string
          }
        }
        multiTab: {
          routeParam: string
          backTab: string
        }
      }
      project: {
        tab: {
          my: string
          star: string
          protocols: string
          members: string
          membersHint: string
          diary: string
          settings: string
        }
        members: string
        protocols: string
        protocolsSearchPlaceholder: string
        protocolsFilter: {
          id: string
          name: string
        }
        protocolsSort: {
          stars: string
          popular: string
          updated: string
        }
        protocolsEmpty: {
          title: string
          description: string
          noResult: string
          searchNoResult: string
          terms: {
            project: {
              title: string
              description: string
            }
            protocol: {
              title: string
              description: string
            }
            record: {
              title: string
              description: string
            }
          }
        }
        protocolFolders: {
          filterLabel: string
          filterAll: string
          filterUncategorized: string
          manageAction: string
          manageTitle: string
          helperHint: string
          manageHint: string
          manageProtocolsAction: string
          manageProtocolsTitle: string
          manageProtocolsHint: string
          namePlaceholder: string
          loading: string
          empty: string
          noProtocols: string
          assignHint: string
          noPermissionHint: string
          renameAction: string
          protocolCount: string
          createSuccess: string
          updateSuccess: string
          saveProtocolsSuccess: string
          saveProtocolsError: string
          loadProtocolsError: string
          deleteSuccess: string
          deleteTitle: string
          deleteDescription: string
        }
        settingsPage: {
          generalTitle: string
          generalDescription: string
          subprojectsTitle: string
          subprojectsDescription: string
          parentProjectTitle: string
          topLevelProjectHint: string
          createSubprojectAction: string
          childProjectsTitle: string
          childProjectsEmpty: string
          subprojectOf: string
          subprojectCountSingle: string
          subprojectCountPlural: string
          logoLabel: string
          logoHint: string
          projectIdLabel: string
          projectIdHint: string
          nameLabel: string
          namePlaceholder: string
          descriptionLabel: string
          descriptionPlaceholder: string
          dangerTitle: string
          dangerDescription: string
          visibilityLabel: string
          changeVisibilityAction: string
          changeVisibilityTitle: string
          changeVisibilityHint: string
          changeAccessRoleAction: string
          changeAccessRoleTitle: string
          changeAccessRoleHint: string
          accessRoleChangeTitle: string
          accessRoleChangeDescription: string
          publicAccessRoleLabel: string
          deleteTitle: string
          deleteDescription: string
          deleteAction: string
          saveAction: string
          deleteEntityName: string
          noChangesTitle: string
          noChangesDescription: string
          visibilityChangeTitle: string
          visibilityChangeDescription: string
          defaultProjectVisibilityHint: string
          defaultProjectDeleteHint: string
          updateError: string
          updateSuccess: string
          fetchError: string
          fetchUpdatedError: string
          deleteError: string
          deleteSuccess: string
          visibility: {
            publicLabel: string
            publicDescription: string
            privateLabel: string
            privateDescription: string
          }
          validation: {
            nameLength: string
            nameEdge: string
            nameRepeat: string
          }
        }
        info: string
        diary: string
        settings: string
        createProjectModal: {
          title: string
          labLabel: string
          parentProjectLabel: string
          parentProjectPlaceholder: string
          parentProjectHint: string
          parentProjectFixedHint: string
          displayNameLabel: string
          displayNamePlaceholder: string
          displayNameTip: string
          projectIdLabel: string
          descriptionPlaceholder: string
          withDiaryLabel: string
          withDiaryOption: string
          withDiaryHint: string
          subprojectVisibilityHint: string
          accessSetupLabel: string
          copyMembersOption: string
          copyMembersHint: string
          labEmptyLabel: string
          labEmptyAction: string
          labRequired: string
          projectIdRequired: string
          displayNameRequired: string
          snakeCaseWarning: string
          creatingWithDiary: string
          diaryCreateFailed: string
          createSuccess: string
          createSuccessWithDiary: string
          projectIdAvailable: string
          labCreateSuccess: string
        }
      }
      protocol: {
        info: string
        protocolName: string
        protocolId: string
        protocolDetails: string
        protocolIdCopied: string
        reusedFrom: string
        settings: {
          basicInfoTitle: string
          basicInfoDescription: string
          protocolIdLabel: string
          protocolVersionLabel: string
          protocolNamePlaceholder: string
          descriptionPlaceholder: string
          disciplinesPlaceholder: string
          keywordsPlaceholder: string
          licensePlaceholder: string
          dangerTitle: string
          dangerDescription: string
          adminViewTitle: string
          adminViewNotice: string
          adminViewDetail: string
          adminViewActionEditInfo: string
          adminViewActionEditEnv: string
          adminViewActionDelete: string
          envTitle: string
          envDescription: string
          envPlaceholder: string
          envRestrictedTitle: string
          envRestrictedDescription: string
          envHidden: string
          envEmpty: string
          envDetectedTitle: string
          envDetectedDescription: string
          envHiddenForSecurity: string
          copy: string
          copied: string
          showValues: string
          hideValues: string
          envEdit: string
          envSave: string
          envSaveSuccess: string
          envSaveFailed: string
          envCopied: string
          saveChanges: string
          deleteTitle: string
          deleteDescription: string
          adminDeleteNotice: string
          validation: {
            nameRequired: string
            nameLength: string
            descriptionLength: string
          }
        }
        tooltips: {
          reuseToProject: string
          editReadOnly: string
          reupload: string
        }
        tab: {
          my: string
          logs: string
          protocols: string
          fields: string
          history: string
          settings: string
          discussion: string
        }
        apply: {
          modalTitle: string
          method: {
            createTitle: string
            updateTitle: string
            createDescription: string
            updateDescription: string
          }
          setup: {
            title: string
            description: string
          }
          steps: {
            allSetTitle: string
            allSetDescription: string
          }
          options: {
            existing: {
              title: string
              description: string
            }
            uploadZip: {
              title: string
              description: string
            }
            scratch: {
              title: string
              description: string
            }
            hub: {
              title: string
              description: string
            }
          }
          setupForm: {
            selectAnotherProtocol: string
            applyToProject: string
            protocolDetailsFork: string
            protocolDetailsReuse: string
            noProtocolSelected: string
            newProtocolDetails: string
            protocolDisplayNameLabel: string
            protocolDisplayNamePlaceholder: string
            protocolIdLabel: string
            protocolIdValid: string
          }
          action: {
            applying: string
            applySuccess: string
            uploadSuccess: string
            applyFailed: string
            applyFailedWithDetail: string
          }
          success: {
            addRecord: string
            redirecting: string
            titleApplied: string
            titleUploaded: string
            descApplied: string
            descUploaded: string
          }
        }
        workflow: {
          ended: string
          workspaceTab: string
          workspaceTabDescription: string
          workspaceHint: string
          workspaceFieldTitle: string
          workspaceFieldHint: string
          openWorkspace: string
          structureTitle: string
          runtimeTitle: string
          protocolCount: string
          titlePlaceholder: string
          defaultGoalLabel: string
          defaultGoalPlaceholder: string
          defaultStrategyLabel: string
          defaultStrategyPlaceholder: string
          logicLabel: string
          logicPlaceholder: string
          selectProtocolPlaceholder: string
          addProtocol: string
          addCurrentProtocol: string
          protocolAlreadyAdded: string
          emptyProtocols: string
          initialProtocolLabel: string
          edgesLabel: string
          emptyEdges: string
          resetRuntime: string
          runtimeEmpty: string
          selectNext: string
          completePrevious: string
          selectUnit: string
          protocolIndex: string
          recordIndex: string
          waitingForRecord: string
          waitingForInitialValues: string
          waitingForIntermediateConclusion: string
          waitingForConclusion: string
          showReport: string
          showIntermediateConclusion: string
          redoRecord: string
          deleteNode: string
          getInitialValues: string
          showInitialValues: string
          addRecord: string
          endWorkflow: string
          end: string
          writeConclusion: string
          writeIntermediateConclusion: string
          selectedProtocol: string
          clickToAddRecord: string
          researchProtocol: string
          aiGenerated: string
          aiGenerateConclusion: string
          intermediateConclusion: string
          intermediateConclusionBase: string
          intermediateConclusionWithSequence: string
          finalConclusionLabel: string
          intermediateConclusionLabel: string
          noResearchNodeSelected: string
          status: {
            init: string
            generating: string
            generated: string
            pending: string
            conclusion: string
            done: string
            error: string
          }
        }
        assignerGraph: {
          dependentField: string
          assigner: string
          assignedField: string
          fullscreenTitle: string
        }
        assignerProgress: {
          completed: string
          assigning: string
          clickForDetails: string
          overallProgress: string
          dependsOn: string
          pending: string
          running: string
          error: string
        }
        fieldInput: {
          title: string
          hint: string
          placeholder: string
          uploadFile: string
          attachmentsHint: string
          attachmentPending: string
          attachmentUploading: string
          attachmentUploaded: string
          unsupportedFileType: string
          fileTooLarge: string
          attachmentUploadFailed: string
          voiceInput: string
          noOperationsRecognized: string
          invalidResponse: string
          operationFailed: string
          noExecutableOperations: string
          unknownField: string
          successUpdated: string
          partialSuccess: string
          allFailed: string
          transcriptionMissing: string
          transcriptionFailed: string
        }
        recordReport: {
          title: string
          protocolDetails: string
          exportPdf: string
          notFoundTitle: string
          notFoundDescription: string
          exportTitle: string
          filenamePlaceholder: string
          saveFilename: string
          editFilename: string
          generatingPdf: string
          generating: string
          protocolNotFound: string
          loadFailed: string
          formRefMissing: string
          noContent: string
          previewFailed: string
          noPdf: string
          exportSuccess: string
          exportFailed: string
        }
        draft: {
          restoreButton: string
          saveButton: string
          title: string
          delete: string
          merge: string
          restoreAction: string
          prompt: string
          previewTitle: string
          previewTab: string
          lastModified: string
          noPreview: string
          noDraft: string
          jsonTab: string
          noJson: string
          cleared: string
        }
        addRecord: {
          viewWorkflowRecord: string
          addToWorkflow: string
          title: string
          noProtocol: string
          uploadPackage: string
          uploadError: string
          uploadSuccess: string
          uploadFailed: string
          workflowContinueTitle: string
          workflowContinueContent: string
          workflowStay: string
          createSuccess: string
          closeWindowTitle: string
          closeWindowContent: string
          noDraftFound: string
        }
        timeline: {
          removeFromChat: string
          addToChat: string
          exportJsonData: string
          viewReport: string
          jsonPreviewTitle: string
          downloadJson: string
          copyToClipboard: string
          previewJson: string
          downloadSuccess: string
          copySuccess: string
          modeTimeline: string
          modePreview: string
        }
        records: {
          advancedSearch: string
          searchContentPlaceholder: string
          searchRecordNumber: string
          recordNumberPlaceholder: string
          searchRecordVersion: string
          recordVersionPlaceholder: string
          protocolVersionLabel: string
          applyFilters: string
          clearAll: string
          bulkImport: string
          bulkImportTitle: string
          bulkImportDropText: string
          bulkImportSupportHint: string
          bulkImportSubmit: string
          bulkImportNoFile: string
          bulkImportCsvOnly: string
          bulkImportSuccess: string
          bulkImportErrorTitle: string
          bulkImportRowError: string
          bulkImportUnknownError: string
          deleteBlockedLatest: string
          deleteBlockedExpired: string
          deleteBlockedLoading: string
          deleteAdminWarning: string
        }
      }
      labs: {
        tab: {
          my: string
          public: string
          members: string
          membersHint: string
          project: string
          protocol: string
          groups: string
          groupsHint: string
          settings: string
        }
        my: string
        public: string
        info: string
        members: string
        projects: string
        groups: string
        settings: string
        searchProjectsPlaceholder: string
        settingsPage: {
          generalTitle: string
          generalDescription: string
          logoLabel: string
          logoHint: string
          labIdLabel: string
          labIdHint: string
          nameLabel: string
          namePlaceholder: string
          descriptionLabel: string
          descriptionPlaceholder: string
          dangerTitle: string
          dangerDescription: string
          deleteTitle: string
          deleteDescription: string
          deleteRequirementsTitle: string
          deleteBlockedHint: string
          deleteReadyHint: string
          deleteReadyWithDefaultProjectsHint: string
          deleteBlockedProjects: string
          deleteBlockedUsers: string
          deleteBlockedDefaultProjectProtocols: string
          deleteModalWarning: string
          deleteErrorHasProjects: string
          deleteErrorHasUsers: string
          deleteErrorDefaultProjectsHaveProtocols: string
          deleteErrorForbidden: string
          deleteError: string
          deleteAction: string
          forceDeleteTitle: string
          forceDeleteDescription: string
          forceDeleteOwnerHint: string
          forceDeleteAction: string
          forceDeletePreviewTitle: string
          forceDeletePreviewDescription: string
          forceDeleteUidLabel: string
          forceDeleteUidPlaceholder: string
          forceDeleteCheckbox: string
          forceDeleteFinalWarning: string
          forceDeleteInProgressDescription: string
          forceDeleteImpactMembers: string
          forceDeleteImpactGroups: string
          forceDeleteImpactProjectsTotal: string
          forceDeleteImpactProjectsActive: string
          forceDeleteImpactProjectsDefault: string
          forceDeleteImpactProtocolsTotal: string
          forceDeleteImpactProtocolsActive: string
          forceDeleteImpactRecordsTotal: string
          forceDeleteImpactRecordsActive: string
          forceDeleteImpactFilesTotal: string
          forceDeleteStarted: string
          forceDeleteSuccess: string
          forceDeleteFailed: string
          forceDeleteFailedWithReason: string
          forceDeletePreviewError: string
          forceDeleteStatusError: string
          forceDeleteErrorForbidden: string
          forceDeleteErrorUidMismatch: string
          forceDeleteErrorIrreversibleRequired: string
          forceDeleteErrorAlreadyInProgress: string
          forceDeleteErrorJobNotFound: string
          forceDeleteError: string
          saveAction: string
          deleteEntityName: string
          infoName: string
          noChangesTitle: string
          noChangesDescription: string
          updateError: string
          updateSuccess: string
        }
        createLabModal: {
          title: string
          displayNameLabel: string
          displayNamePlaceholder: string
          displayNameTip: string
          labIdLabel: string
          descriptionPlaceholder: string
          logoLabel: string
          defaultProjectsTitle: string
          defaultProjectsIntro: string
          defaultProjectsPublic: string
          defaultProjectsPrivate: string
          snakeCaseWarning: string
          createSuccessWithDefaults: string
          defaultProjectsWarning: string
          labIdAvailable: string
        }
        searchMyLabsPlaceholder: string
        searchLabIdLabel: string
        searchLabNameLabel: string
        searchEmptyById: string
        searchEmptyByName: string
      }
      profile: {
        info: string
        summary: string
        protocols: string
        starred: string
        settings: string
        setting: string
        apiKeySetting: string
        account: string
        userSettings: string
        changePhone: string
        changePassword: string
        changePasswordDescription: string
        changePasswordSuccess: string
        changePasswordFailure: string
        currentPassword: string
        newPassword: string
        confirmPassword: string
        passwordMismatch: string
        savePassword: string
        forgotPassword: string
        verifyCurrentPhone: string
        verifyNewPhone: string
        enterCurrentPhone: string
        enterCurrentPhoneDescription: string
        sendSmsToCurrentPhone: string
        sendSmsToCurrentPhoneDescription: string
        sendCodeToCurrentPhone: string
        yourCurrentPhone: string
        noPhoneNumber: string
        sendCodeTo: string
        enterNewPhone: string
        enterNewPhoneDescription: string
        sendSmsToNewPhone: string
        sendSmsToNewPhoneDescription: string
        phoneOrCountryCodeMissing: string
        changePhoneSuccess: string
        changePhoneFailure: string
        enterCodeForPhone: string
        enterCodeForNewPhone: string
        confirmPhoneChange: string
        phoneMismatch: string
        newPhoneMustBeDifferent: string
      }
      group: {
        createGroupTitle: string
        addProjectToGroup: string
        addProjectModal: {
          targetGroupLabel: string
          targetGroupPlaceholder: string
          projectLabel: string
        }
        projects: string
        members: string
        settings: string
        createGroupModal: {
          displayNameLabel: string
          displayNamePlaceholder: string
          displayNameTip: string
          groupIdLabel: string
          descriptionPlaceholder: string
          selectProjectsLabel: string
          selectProjectsPlaceholder: string
          labNotFound: string
          snakeCaseWarning: string
          createSuccess: string
          groupIdAvailable: string
        }
      }
      search: {
        protocol: string
        record: string
        discussion: string
        title: string
      }
      hub: {
        title: string
        openHub: string
        uploadProtocol: string
        searchPlaceholder: string
        recordsEmpty: string
        downloadsStatsTitle: string
        category: {
          biology: string
          chemistry: string
          physics: string
        }
        sort: {
          popularity: string
          recentlyUpdated: string
          bestMatch: string
        }
        dashboard: {
          title: string
          myProtocols: string
          analytics: string
          settings: string
          analyticsPlaceholder: string
          settingsPlaceholder: string
          sampleProtocolName: string
        }
        uploadModal: {
          title: string
          protocolNameLabel: string
          protocolNamePlaceholder: string
          protocolFileLabel: string
        }
        protocolCard: {
          addToBookmarks: string
        }
        protocolUpload: {
          stepApplyToProject: string
          stepSelectPackage: string
          stepConfigureProtocol: string
          stepEnvConfig: string
          uploadInstructionZip: string
          uploadInstructionFile: string
          uploadSupportTypes: string
          emptySelectPackage: string
          addEnvFile: string
          uploadEnvTitle: string
          uploadEnvHint: string
          labProjectRequired: string
          changeVersion: string
          updateVersionTooltip: string
          projectRequired: string
          envFilesOnly: string
          fileExistsTitle: string
          overrideConfirm: string
        }
        envEditor: {
          handlingTitle: string
          handlingItem1: string
          handlingItem2: string
          handlingItem3: string
          handlingItem4: string
          handlingItem5: string
          handlingItem6: string
          summaryTitle: string
          summaryTooltip: string
          totalFiles: string
          filesToInclude: string
          filesToExclude: string
          filesTitle: string
          filesTooltip: string
          removeConfirm: string
          contentPlaceholder: string
          includeLabel: string
          excludeLabel: string
        }
      }
    }
    form: {
      required: string
      fieldRequired: string
      username: {
        required: string
        invalid: string
        length: string
        pattern: string
        startLowercase: string
        hyphenEdges: string
        hyphenConsecutive: string
      }
      phone: {
        required: string
        invalid: string
      }
      pwd: {
        required: string
        invalid: string
      }
      confirmPwd: {
        required: string
        invalid: string
      }
      code: {
        required: string
        invalid: string
      }
      email: {
        required: string
        invalid: string
      }
      uid: {
        length: string
        pattern: string
        hyphenEdges: string
        hyphenConsecutive: string
        startLowercase: string
      }
      displayName: {
        length: string
        hyphenEdges: string
        hyphenConsecutive: string
      }
      password: {
        uppercase: string
        lowercase: string
        digit: string
        specialMissing: string
        specialUnsupported: string
        length: string
      }
      version: {
        invalid: string
      }
      file: {
        required: string
        nameRequired: string
        nameInvalid: string
        nameStartsDot: string
        nameMissing: string
        typeInvalid: string
        validationFailed: string
        renameSuccess: string
        uploadFailed: string
        invalidFile: string
        sizeLimit: string
        maxCount: string
      }
    }
    dropdown: {
      closeCurrent: string
      closeOther: string
      closeLeft: string
      closeRight: string
      closeAll: string
    }
    icon: {
      themeConfig: string
      themeSchema: string
      lang: string
      fullscreen: string
      fullscreenExit: string
      reload: string
      collapse: string
      expand: string
      pin: string
      unpin: string
    }
    role: {
      owner: string
      member: string
      manager: string
      collaborator: string
      recorder: string
      recorder_self_only: string
      explorer: string
      explorer_self_only: string
      viewer: string
      viewer_self_only: string
      description: {
        project: {
          owner: string
          manager: string
          collaborator: string
          recorder: string
          recorderPublic: string
          recorderSelfOnly: string
          explorer: string
          explorerSelfOnly: string
          viewer: string
          viewerSelfOnly: string
        }
        lab: {
          owner: string
          manager: string
          member: string
        }
      }
      permission: {
        project: {
          owner: {
            setManager: string
          }
          manager: {
            assignRole: string
            manageProtocols: string
            deleteOwnRecords: string
            deleteOthersRecords: string
          }
          collaborator: {
            createProtocol: string
            manageOwnProtocol: string
            viewOthersRecords: string
          }
          recorder: {
            createProtocol: string
            manageOwnProtocol: string
            submitRecords: string
            viewOwnRecords: string
          }
          explorer: {
            openDataEntry: string
          }
          viewer: {
            previewPublicProtocols: string
          }
        }
        lab: {
          owner: {
            setManager: string
          }
          manager: {
            assignRole: string
            manageGroups: string
            deleteOwnRecords: string
            deleteOthersRecords: string
          }
          member: {
            createProject: string
            manageOwnProject: string
            viewOthersProtocols: string
          }
        }
      }
    }
    breadcrumb: {
      groups: string
      myProjects: string
      starredProjects: string
      allProjects: string
      addNewProject: string
      allLabs: string
      addNewLab: string
      allProtocols: string
      addNewProtocol: string
      allMembers: string
      inviteMember: string
      myLabs: string
      publicLabs: string
      myProfile: string
      allProfile: string
      hubAll: string
    }
    chat: {
      newChatButton: string
      newChatTitle: string
      askAira: string
      dragToMove: string
      airaIntroTitle: string
      airaIntroSubtitle: string
      airaDisclaimer: string
      inputPlaceholder: string
      loadMoreMessages: string
      scrollToBottom: string
      dock: string
      fullScreen: string
      collapse: string
      expand: string
      addToChat: string
      dropzoneHint: string
      examples: {
        protocol: {
          brief: string
          criticalPoints: string
          optimize: string
          safety: string
        }
        hub: {
          tumorInhibition: string
          drugTreatmentAnalysis: string
          nanotechnology: string
        }
      }
      history: string
      placeholder: string
      placeholderMobile: string
      copy: string
      copied: string
      copyCode: string
      copyFailed: string
      clearChat: string
      clearChatConfirm: string
      exportImage: string
      exportImageConfirm: string
      exportSuccess: string
      exportFailed: string
      usingContext: string
      turnOnContext: string
      turnOffContext: string
      deleteMessage: string
      deleteMessageConfirm: string
      deleteHistoryConfirm: string
      clearHistoryConfirm: string
      preview: string
      showRawText: string
      thinking: string
      enableThinking: string
      thinkingEnabled: string
      enableSearch: string
      searchEnabled: string
      enableHubSearch: string
      hubSearchEnabled: string
      model: {
        select: string
        basic: string
        plus: string
        pro: string
        gpt: string
      }
      editorCodeEdit: {
        tooltip: string
        emptyPrompt: string
        noFiles: string
        running: string
        changedSummary: string
        noChanges: string
        failed: string
        reviewTitle: string
        warnings: string
        executionLog: string
        apply: string
        applyAll: string
        close: string
        diffFallback: string
        applySuccess: string
        applyAllSuccess: string
        unsupportedFile: string
        emptyResult: string
        status: {
          created: string
          modified: string
          deleted: string
        }
      }
      common: {
        add: string
        addSuccess: string
        edit: string
        editSuccess: string
        delete: string
        deleteSuccess: string
        save: string
        saveSuccess: string
        reset: string
        action: string
        export: string
        exportSuccess: string
        import: string
        importSuccess: string
        clear: string
        clearSuccess: string
        yes: string
        no: string
        confirm: string
        download: string
        noData: string
        wrong: string
        success: string
        failed: string
        verify: string
        unauthorizedTips: string
        stopResponding: string
      }
    }
    editor: {
      landing: {
        eyebrow: string
        title: string
        description: string
        startLabel: string
        actions: {
          template: {
            title: string
            description: string
          }
          hub: {
            title: string
            description: string
          }
          clone: {
            title: string
            description: string
          }
          upload: {
            title: string
            description: string
          }
        }
        uploadTitle: string
        uploadApply: string
        cloneTitle: string
        cloneDescription: string
        cloneAction: string
        selectProtocolWarning: string
        missingProjectError: string
        cloneFailed: string
        cloneSuccess: string
        createSuccess: string
        createFailed: string
        uploadSelectWarning: string
        uploadSuccess: string
        uploadFailed: string
      }
      extensions: {
        Raw: {
          markdown: {
            title: string
            tooltip: string
          }
          richText: {
            title: string
            tooltip: string
          }
        }
        Bold: {
          tooltip: string
        }
        Underline: {
          tooltip: string
        }
        Italic: {
          tooltip: string
        }
        Strike: {
          tooltip: string
        }
        Heading: {
          tooltip: string
          buttons: {
            paragraph: string
            heading: string
          }
        }
        Blockquote: {
          tooltip: string
        }
        CodeBlock: {
          tooltip: string
        }
        Link: {
          add: {
            tooltip: string
            control: {
              title: string
              name: string
              href: string
              open_in_new_tab: string
              confirm: string
              cancel: string
            }
          }
          edit: {
            tooltip: string
            control: {
              title: string
              name: string
              href: string
              open_in_new_tab: string
              confirm: string
              cancel: string
            }
          }
          unlink: {
            tooltip: string
          }
          open: {
            tooltip: string
          }
        }
        Image: {
          buttons: {
            insert_image: {
              tooltip: string
              external: string
              upload: string
            }
            remove_image: {
              tooltip: string
            }
            image_options: {
              tooltip: string
            }
            display: {
              tooltip: string
              inline: string
              block: string
              left: string
              right: string
            }
          }
          control: {
            insert_by_url: {
              title: string
              placeholder: string
              confirm: string
              cancel: string
              invalid_url: string
            }
            upload_image: {
              title: string
              button: string
            }
            edit_image: {
              title: string
              confirm: string
              cancel: string
              form: {
                src: string
                alt: string
                width: string
                height: string
              }
            }
          }
        }
        Iframe: {
          tooltip: string
          control: {
            title: string
            placeholder: string
            confirm: string
            cancel: string
          }
        }
        BulletList: {
          tooltip: string
        }
        OrderedList: {
          tooltip: string
        }
        TodoList: {
          tooltip: string
        }
        TextAlign: {
          tooltip: string
          buttons: {
            align_left: {
              tooltip: string
              label: string
            }
            align_center: {
              tooltip: string
              label: string
            }
            align_right: {
              tooltip: string
              label: string
            }
            align_justify: {
              tooltip: string
              label: string
            }
          }
        }
        FontFamily: {
          tooltip: string
        }
        FontSize: {
          tooltip: string
          default: string
        }
        TextColor: {
          tooltip: string
        }
        TextHighlight: {
          tooltip: string
        }
        LineHeight: {
          tooltip: string
        }
        Table: {
          tooltip: string
          buttons: {
            insert_table: string
            add_column_before: string
            add_column_after: string
            delete_column: string
            add_row_before: string
            add_row_after: string
            delete_row: string
            merge_cells: string
            split_cell: string
            delete_table: string
          }
        }
        Indent: {
          buttons: {
            indent: {
              tooltip: string
            }
            dedent: {
              tooltip: string
            }
          }
        }
        FormatClear: {
          tooltip: string
        }
        HorizontalRule: {
          tooltip: string
        }
        History: {
          tooltip: {
            undo: string
            redo: string
          }
        }
        Fullscreen: {
          tooltip: {
            fullscreen: string
            exit_fullscreen: string
          }
        }
        Print: {
          tooltip: string
        }
        Preview: {
          tooltip: string
          dialog: {
            title: string
          }
        }
        SelectAll: {
          tooltip: string
        }
        CodeView: {
          tooltip: string
        }
        Collapsed: {
          tooltip: string
        }
        Uncollapsed: {
          tooltip: string
        }
      }
      characters: string
    }
  }
}
