"""Independent fake transport, not a test generated by the source proposal."""

import threading
import unittest
from types import SimpleNamespace
from unittest.mock import patch

from controlled_reader import ControlledReader, create_adapter


class IndependentController:
    def __init__(self):
        self.state, self.owner = "idle", "gateway"
        self.operator_confirmed, self.ready = True, True
        self.starts, self.stops = 0, 0
        self.count = None
        self.change_on_poll = None
        self.fail_stop = False

    def identity(self):
        return {"fixture_identity": "independently supplied"}

    def configure(self, count):
        self.count = count

    def parameters(self):
        return {"sample_count": self.count}

    def start(self):
        self.starts += 1
        self.state = "running"

    def poll(self):
        if self.change_on_poll:
            self.change_on_poll()
        if self.state == "running":
            self.state = "complete"
        return self.state

    def result(self):
        # Intentionally differs from the source-included simulator's formula.
        return {
            "sample_count": self.count,
            "value": 17.75,
            "unit": "synthetic_unit",
            "simulation_only": True,
        }

    def stop(self):
        self.stops += 1
        if not self.fail_stop:
            self.state = "stopped"


class ControlledContractTests(unittest.TestCase):
    def setUp(self):
        self.controller = IndependentController()
        self.adapter = ControlledReader(self.controller)
        self.stop = threading.Event()
        self.job = SimpleNamespace(
            command_key="reader.measure",
            command_version="1.0.0",
            arguments={"sample_count": 4},
        )

    def test_reads_independent_values_and_starts_once(self):
        self.assertEqual(self.adapter.identity(), self.controller.identity())
        self.assertTrue(self.adapter.confirm(self.job))
        self.assertTrue(self.adapter.preflight(self.job)["interlocks"]["reader.ready"])
        self.assertEqual(self.adapter.execute(self.job, self.stop)["value"], 17.75)
        self.assertEqual(self.controller.starts, 1)
        with self.assertRaises(RuntimeError):
            self.adapter.execute(self.job, self.stop)
        self.assertEqual(self.controller.starts, 1)

    def test_parameter_mismatch_and_false_confirmation_never_start(self):
        self.controller.parameters = lambda: {"sample_count": 3}
        with self.assertRaises(RuntimeError):
            self.adapter.execute(self.job, self.stop)
        self.assertEqual(self.controller.starts, 0)
        self.controller.operator_confirmed = False
        self.assertIsNone(self.adapter.confirm(self.job))
        self.assertFalse(self.adapter.preflight(self.job)["operator_present"])
        with self.assertRaises(RuntimeError):
            self.adapter.execute(self.job, self.stop)
        self.assertEqual(self.controller.starts, 0)

    def test_boolean_parameter_readback_and_completion_timeout_fail(self):
        self.job.arguments["sample_count"] = 1
        self.controller.parameters = lambda: {"sample_count": True}
        with self.assertRaises(RuntimeError):
            self.adapter.execute(self.job, self.stop)
        self.assertEqual(self.controller.starts, 0)
        self.controller.parameters = lambda: {"sample_count": self.controller.count}
        with (
            patch("controlled_reader.time.monotonic", side_effect=[0, 6]),
            self.assertRaises(RuntimeError),
        ):
            self.adapter.execute(self.job, self.stop)
        self.assertEqual(self.controller.starts, 1)

    def test_changed_state_during_configuration_never_starts(self):
        def configure(count):
            self.controller.count = count
            self.controller.state = "running"

        self.controller.configure = configure
        with self.assertRaises(RuntimeError):
            self.adapter.execute(self.job, self.stop)
        self.assertEqual(self.controller.starts, 0)

    def test_takeover_during_final_readback_is_not_completion(self):
        def parameters():
            if self.controller.state == "complete":
                self.controller.owner = "human"
            return {"sample_count": self.controller.count}

        self.controller.parameters = parameters
        with self.assertRaises(RuntimeError):
            self.adapter.execute(self.job, self.stop)
        self.assertEqual(self.controller.starts, 1)

    def test_takeover_and_cancellation_are_failures_not_completion(self):
        self.controller.change_on_poll = lambda: setattr(
            self.controller, "owner", "human"
        )
        with self.assertRaises(RuntimeError):
            self.adapter.execute(self.job, self.stop)
        self.assertEqual(self.controller.starts, 1)
        self.adapter.safe_stop(self.job, "takeover")
        self.assertEqual(self.controller.state, "stopped")
        self.adapter.safe_stop(self.job, "receipt replay")
        self.assertEqual(self.controller.stops, 1)
        self.setUp()
        self.controller.change_on_poll = self.stop.set
        with self.assertRaises(RuntimeError):
            self.adapter.execute(self.job, self.stop)
        self.assertEqual(self.controller.starts, 1)

    def test_unconfirmed_stop_is_not_reported_as_safe(self):
        self.controller.state = "running"
        self.controller.fail_stop = True
        with self.assertRaises(RuntimeError):
            self.adapter.safe_stop(self.job, "synthetic fault")
        self.assertEqual(self.controller.state, "running")

    def test_lost_start_response_never_repeats_start(self):
        def lose_response():
            self.controller.starts += 1
            self.controller.state = "running"
            raise ConnectionError("Owned synthetic lost receipt")

        self.controller.start = lose_response
        with self.assertRaises(ConnectionError):
            self.adapter.execute(self.job, self.stop)
        self.assertEqual(self.controller.starts, 1)
        self.adapter.safe_stop(self.job, "uncertain start")
        self.assertEqual(self.controller.starts, 1)
        self.assertEqual(self.controller.state, "stopped")

    def test_mismatched_completion_and_invalid_arguments_fail(self):
        self.controller.result = lambda: {
            "sample_count": 4,
            "value": 17.75,
            "unit": "different",
            "simulation_only": True,
        }
        with self.assertRaises(ValueError):
            self.adapter.execute(self.job, self.stop)
        for count in (True, 0, 97):
            self.job.arguments = {"sample_count": count}
            with self.assertRaises(ValueError):
                self.adapter.execute(self.job, self.stop)
        self.job.command_key = "unknown"
        with self.assertRaises(ValueError):
            self.adapter.execute(self.job, self.stop)
        with self.assertRaises(ValueError):
            create_adapter("production.json")
        self.assertTrue(create_adapter(None).identity()["firmware"] == "simulation")


if __name__ == "__main__":
    unittest.main()
