/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconBxFontSize: typeof import('~icons/bx/font-size')['default']
    IconIonAddOutline: typeof import('~icons/ion/add-outline')['default']
    IconIonArrowUp: typeof import('~icons/ion/arrow-up')['default']
    IconIonChevronDown: typeof import('~icons/ion/chevron-down')['default']
    IconIonChevronForward: typeof import('~icons/ion/chevron-forward')['default']
    IconIonChevronForwardCircleOutline: typeof import('~icons/ion/chevron-forward-circle-outline')['default']
    IconIonChevronUp: typeof import('~icons/ion/chevron-up')['default']
    IconIonCloudUploadOutline: typeof import('~icons/ion/cloud-upload-outline')['default']
    IconIonIosArrowDown: typeof import('~icons/ion/ios-arrow-down')['default']
    IconIonLanguage: typeof import('~icons/ion/language')['default']
    IconIonOpenOutline: typeof import('~icons/ion/open-outline')['default']
    IconIonPersonOutline: typeof import('~icons/ion/person-outline')['default']
    IconMageSoundWaves: typeof import('~icons/mage/sound-waves')['default']
    IconMaterialSymbolsClose: typeof import('~icons/material-symbols/close')['default']
    IconSharedAiralogyChat: typeof import('~icons/shared/airalogy-chat')['default']
    IconSharedAiralogyLogo: typeof import('~icons/shared/airalogy-logo')['default']
    IconSharedProtocolOutline: typeof import('~icons/shared/protocol-outline')['default']
    IconSharedRecordOutline: typeof import('~icons/shared/record-outline')['default']
    IconSharedSendMessage: typeof import('~icons/shared/send-message')['default']
    IconSharedStopMessage: typeof import('~icons/shared/stop-message')['default']
    IconTablerCheck: typeof import('~icons/tabler/check')['default']
    IconTablerCopy: typeof import('~icons/tabler/copy')['default']
    IconTablerFile: typeof import('~icons/tabler/file')['default']
    IconTablerPinned: typeof import('~icons/tabler/pinned')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopover: typeof import('naive-ui')['NPopover']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NUpload: typeof import('naive-ui')['NUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
