import type { FieldKey } from "@airalogy/aimd-core/types"

/**
 * Main Structure
 */
export interface Assigner {
  /** Stable assigner id when provided by AIMD parser */
  id?: string
  /** Runtime discriminator for client/server assigners */
  runtime?: "client" | "server"
  /**
        Assign mode.
        Functions decorated with `assigner` can be triggered via a button on the frontend. Each invocation triggers a backend request to use the decorated function to generate the target RV (Research Variable) value. The reason for this design is that the generation of some RV values depends on the values of other RVs input by the user on the frontend. Therefore, during value initialization, these RV values cannot be initialized and can only be generated by triggering the backend calculation via a frontend button after the user has completed the input.
        - Mode 1: `manual`. The frontend user must manually click the button to trigger the backend calculation.
        - Mode 2: `auto_first`. When the dependent RV values are initialized, the backend automatically calculates and generates the target RV value. However, if the user subsequently adjusts the dependent RV values, the target RV value will not be re-calculated automatically.
        - Mode 3: `auto`. When the dependent RV values are initialized, the backend automatically calculates and generates the target RV value. If the user subsequently adjusts the dependent RV values, the target RV value will be re-calculated automatically.
        - Mode 4: `auto_force`. When the dependent RV values are initialized, the backend automatically calculates and generates the target RV value. If the user subsequently adjusts the dependent RV values, the target RV value will be re-calculated automatically. `force` means that the assigned RV is forcibly calculated automatically; regardless of whether the user clicks the button, as long as the dependent RV values change, the target RV value will be re-calculated automatically, and the user cannot modify the assigned RV value on the frontend.
   */
  mode: "auto" | "manual" | "auto_first" | "auto_force"
  dependent_fields: string[]
  /** Fields written by the assigner under the latest AIMD syntax */
  assigned_fields?: string[]
  /** Extracted function source for client assigners */
  function_source?: string
}

export interface ProtocolResponseInfo {
  id: string
  project_id: string
  project_uid?: string
  project_name?: string
  lab_id: string
  lab_uid?: string
  lab_name?: string
  user_id: string
  uid: string
  name: string
  description?: string
  created_at: string
  updated_at: string
  parent_protocol_id?: string | null
  parent_protocol_version?: string | null
  stars_count: number
  status: 1
  keywords: string[]
  disciplines: string[]
  forks_count: number
  latest_version: string
}

export interface ProtocolVersion extends Pick<ProjectProtocolInfo, "id" | "protocol_id" | "version" | "created_at" | "updated_at" | "aimd" | "airalogy_id" | "assigner" | "authors" > {
  version: string
  protocol_id: string
  meta_data: ProtocolMetaData
}

export interface ProtocolInfo<T = FieldKey> extends ProtocolResponseInfo {
  fields: Fields<T>
  json_schema: JsonSchema
  aimd: string
  // meta_data: ProtocolMetaData
  assigners: Record<string, Assigner>
  airalogy_id: string
}
export interface ProtocolPerson {
  name: string
  email: string
  airalogy_user_id: string
}

export interface ProtocolMetaData {
  id: string
  version: string
  airalogy_protocol_id?: string
  name: string
  authors: ProtocolPerson[]
  maintainers: ProtocolPerson[]
  disciplines: string[]
  keywords: string[]
  license: string
  created_at?: string
  description?: string
}

export interface FieldItem {
  name: string
  line_number: number
  check?: boolean
  /** rs level */
  step_level?: number
  check_message?: string
  input_type?: string
  /** @deprecated use airalogy_types instead */
  airalogy_built_in_type?:
    | "png"
    | "jpg"
    | "svg"
    | "webp"
    | "tiff"
    | "mp4"
    | "mp3"
    | "rnmd"
    | "md"
    | "txt"
    | "csv"
    | "json"
    | "docx"
    | "xlsx"
    | "pptx"
    | "pdf"
    | "FileId"
  airalogy_type?:
    | "png"
    | "jpg"
    | "svg"
    | "webp"
    | "tiff"
    | "mp4"
    | "mp3"
    | "rnmd"
    | "md"
    | "txt"
    | "csv"
    | "json"
    | "docx"
    | "xlsx"
    | "pptx"
    | "pdf"
    | "FileId"
  /** @deprecated syntax for airalogy_built_in_type */
  build_in_rv_type?: string
  /** ref_step */
  sequence?: number
  detail?: string

  /** var_table */
  subvars?: string[]
  type?: string
  file_extension?: string
  link?: {
    source: { name: string, prop: string }
    target: { name: string, prop: string }
  }
  assigner?: Assigner
  dependent?: { name: string, scope: IRecordDataKey }[]
}
/**
 * User interface fields
 */
export type Fields<T = FieldKey> = { [K in T]: FieldItem[] }

export interface JsonSchema {
  research_check: ResearchCheckpoint
  research_result: ResearchResult
  research_step: ResearchStep
  research_variable: ResearchVariable
}

export interface ResearchNodeProp {
  properties: Record<string, DataObject>
  required: string[]
  title: string
  description?: string
  type: string
  enum?: string | number[]
  $defs?: Record<string, ResearchNodeProp>
}

export interface ResearchCheckpoint extends ResearchNodeProp { }
export interface ResearchResult extends ResearchNodeProp { }
export interface ResearchStep extends ResearchNodeProp { }

export interface ResearchVariable extends ResearchNodeProp { }

export interface DataObject {
  format: string
  title: string
  type: string
  default?: string | number | boolean | { rrec_airalogy_id?: string }
  /** type: array */
  items?: {
    /** #/$defs/PCRDNAGroups */
    $ref: string
    airalogy_built_in_type?: string
    description?: string
    examples?: string[]
    type?: string
    properties?: Record<string, DataObject>
  }
  enum?: any[]
  airalogy_built_in_type?: FieldItem["airalogy_built_in_type"]
  /** @deprecated */
  build_in_rv_type?: "UserName" | "CurrentTime" | "Md" | "FileId"
  $ref?: string
  description?: string
  examples?: string[]
  file_extension?: string

  // items.airalogy_built_in_type === RecordId
  recommended_protocol_id?: string
}

export interface AnyOf {
  format?: string
  type: string
}

export interface ApplyProtocolRequestPayload {
  labUid: string | null
  projectUid: string | null
  // protocolUid: string | null
  description: string
  // categories: string[]
  tags: string[]
  version: string
  isPublic: boolean
  protocolUid: string | null
  protocolId: string | null
}
export interface ForkProtocolRequestPayload {
  parentProtocolId: string
  projectId: string
  protocolName: string
  protocolUid: string
}
export interface ProjectProtocolInfo extends ProtocolInfo {
  // lab_id: string
  // lab_name: string
  // lab_uid: string
  lab: {
    id: string
    name: string
    uid: string
  }
  project: {
    id: string
    name: string
    uid: string
  }
  updated_at: string
  user_id: string
  // protocol?: Protocol.ProtocolInfo
  user: {
    name: string
    id: string
    username: string
  }
  user_id: string
  records_count: number
  metadata: ProtocolMetaData
  folder_ids?: number[]
}

export interface ProtocolItem {
  id: string
  uid: string
  name: string
  label: string
  owner: Pick<Auth.UserInfo, "id" | "username">
  createdAt: string
  project: Project.MyProjectInfo
  projectName: string
  groupName: string
  avatar?: string
  protocolCount: number
  group_id: string
}

// interface ProtocolItem {
//   id: string
//   package: PackageFiled
//   history: HistoryItem[]
// }

export interface RecordInfo {
  // created_at: string
  // protocol_id: string
  // id: string
  // report: string
  // data: Partial<Record<Markdown.FiledName | FieldKey, (string | [string, string[]])[]>>
  // protocol_id: string
  // updated_at: string
  // user_id: string
  // user_name: string
  // user_username: string
  // hash: string
  // number: number
  // version: number
  // protocol?: Protocol.ProtocolInfo

  airalogy_record_id: string
  data: Partial<Record<Markdown.FiledName | FieldKey, (string | [string, string[]])[]>>
  metadata: RecordMetadata
  record_id: string
  record_version: number
}

export interface RecordMetadata {
  airalogy_protocol_id: string
  /** Lab UID */
  lab_id: string
  /** Project UID */
  project_id: string
  /** Protocol UUID */
  protocol_id: string
  protocol_version: string
  record_current_version_submission_time: string
  record_current_version_submission_user_id: string
  record_initial_version_submission_time: string
  record_initial_version_submission_user_id: string
  record_num: number
  sha1: string
}
export interface RvAssignerItem {
  success: boolean
  assigned_fields: Record<string, any>
  error_message: string | null
}

export interface ForkedProtocolResponse extends ProtocolInfo {
}

export interface EnvVar {
  env_vars: Record<string, string>
}
