import { Buffer } from "node:buffer"
import { expect, test } from "@playwright/test"

test("standard CSV template, validation and explicit import create real Records", async ({ page }) => {
  test.setTimeout(120_000)
  await page.addInitScript(() => localStorage.setItem("lang", JSON.stringify({ data: sessionStorage.getItem("csv-test-language") || "en-US", expire: null })))
  await page.goto("/labs/dev_lab/projects/quickstart/protocols")
  await page.getByRole("button", { name: "New protocol", exact: true }).click()
  await page.getByTestId("protocol-create-template").click()
  await page.getByTestId("template-name").locator("input").fill("CSV import practice")
  await page.getByTestId("template-create-confirm").click()
  await expect(page.getByRole("dialog")).toHaveCount(0)
  await page.getByRole("button", { name: "Save", exact: true }).click()
  const published = page.waitForResponse(response => new URL(response.url()).pathname === "/api/protocols" && response.request().method() === "POST")
  await page.getByRole("dialog").getByRole("button", { name: "Save", exact: true }).click()
  const response = await published
  expect(response.ok(), await response.text()).toBeTruthy()
  const { data: protocol } = await response.json()
  await page.getByRole("button", { name: "Open Protocol", exact: true }).click()
  await expect(page).toHaveURL(/\/protocols\/protocol_/)
  await page.goto(`${new URL(page.url()).pathname.replace(/\/protocol$/, "")}/records`)
  await page.getByRole("button", { name: "Bulk upload", exact: true }).click()
  const dialog = page.getByRole("dialog")
  await expect(dialog).toContainText("CSV import practice")
  const download = page.waitForEvent("download")
  await dialog.getByRole("button", { name: "Download CSV template" }).click()
  const stream = await (await download).createReadStream()
  const chunks: Buffer[] = []
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk))
  expect(Buffer.concat(chunks).toString("utf8")).toBe("\uFEFFvar.sample_label,var.observation_count,var.notes\r\n")

  const upload = dialog.locator("input[type=file]")
  await upload.setInputFiles({ name: "invalid.csv", mimeType: "text/csv", buffer: Buffer.from("var.sample_label,var.observation_count,unknown\nSYNTHETIC-001,0,\n") })
  await dialog.getByRole("button", { name: "Validate file", exact: true }).click()
  await expect(dialog).toContainText("Correct the file and validate again (not imported)")
  await expect(dialog).toContainText("unknown")
  await expect(dialog.getByRole("button", { name: "Confirm import", exact: true })).toBeDisabled()

  // Replace rather than append the selected file. Zero is an actual observation.
  await dialog.locator(".n-upload-file-list .n-button").last().click()
  await upload.setInputFiles({ name: "valid.csv", mimeType: "text/csv", buffer: Buffer.from("\uFEFFvar.observation_count,var.sample_label\n0,SYNTHETIC-001\n2,SYNTHETIC-002\n") })
  const previewResponse = page.waitForResponse(response => response.url().endsWith(`/api/protocols/${protocol.id}/records/import`))
  await dialog.getByRole("button", { name: "Validate file", exact: true }).click()
  const preview = await previewResponse
  expect((await preview.json()).valid_count).toBe(2)
  const headers = await preview.request().allHeaders()
  const readRecords = () => page.request.get(`/api/protocols/${protocol.id}/records`, { headers: { "Auth-Token": headers["auth-token"] } })
  expect((await (await readRecords()).json()).total_count).toBe(0)
  await expect(dialog).toContainText("Validation passed (not imported)")
  await expect(dialog.getByRole("button", { name: "Confirm import", exact: true })).toBeDisabled()
  await page.setViewportSize({ width: 390, height: 844 })
  const bounds = await dialog.boundingBox()
  expect(bounds?.x).toBeGreaterThanOrEqual(15)
  expect((bounds?.x || 0) + (bounds?.width || 0)).toBeLessThanOrEqual(375)
  await page.screenshot({ path: test.info().outputPath("csv-preview-mobile.png") })
  await dialog.getByRole("checkbox").check()
  const imported = page.waitForResponse(response => response.url().endsWith(`/api/protocols/${protocol.id}/records/import`))
  await dialog.getByRole("button", { name: "Confirm import", exact: true }).click()
  const saved = await imported
  expect(saved.ok(), await saved.text()).toBeTruthy()
  expect((await saved.json()).imported_count).toBe(2)
  await expect(dialog).toHaveCount(0)
  await page.reload()
  await expect(page.getByText("SYNTHETIC-001", { exact: true })).toBeVisible()
  await expect(page.getByText("SYNTHETIC-002", { exact: true })).toBeVisible()
  expect((await (await readRecords()).json()).total_count).toBe(2)

  // The same narrow-screen flow also presents actionable Chinese errors.
  await page.evaluate(() => sessionStorage.setItem("csv-test-language", "zh-CN"))
  await page.reload()
  await page.getByRole("button", { name: "批量上传", exact: true }).click()
  await expect(dialog.getByRole("button", { name: "下载 CSV 模板", exact: true })).toBeEnabled()
  await upload.setInputFiles({ name: "invalid.csv", mimeType: "text/csv", buffer: Buffer.from("var.sample_label,var.observation_count\nSYNTHETIC-003,#REF!\n") })
  await dialog.getByRole("button", { name: "预检文件", exact: true }).click()
  await expect(dialog).toContainText("请修正后重新预检（尚未导入）")
  await expect(dialog).toContainText("存在表格错误值")
  await expect(dialog.getByRole("button", { name: "确认导入", exact: true })).toBeDisabled()
  expect((await (await readRecords()).json()).total_count).toBe(2)
  await dialog.getByText("存在表格错误值", { exact: false }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: test.info().outputPath("csv-errors-mobile-zh.png") })
})
