import type { ResearchAction, ResearchTaskDetail } from "../../../apps/web/src/service/api/research-tasks"
import type { WorkflowAnalysisPublication, WorkflowAnalysisPublicationPreview } from "../../../apps/web/src/service/api/workflow-analysis-methods"
import type { WorkflowContext, WorkflowDefinitionDetail, WorkflowRunPreview, WorkflowSavePreview } from "../../../apps/web/src/service/api/workflow-definitions"
import { randomUUID } from "node:crypto"
import { expect, test } from "@playwright/test"
import { loadFixtures, selectVisibleOption } from "./fixtures"

// Real disposable API/DB throughout. These tests neither request a model nor
// authorize instruments. Runtime Record acceptance is covered by PostgreSQL tests.
for (const locale of ["en-US", "zh-CN"] as const) {
  test(`Protocol card Workflow saves immutable revisions and starts governed actions without AI (${locale})`, async ({ page, request }, testInfo) => {
    const fixtures = await loadFixtures()
    const api = process.env.E2E_API_URL || "http://127.0.0.1:4100"
    const signin = await request.post(`${api}/signin_by_email`, { data: { email: "dev.owner@airalogy.dev", password: "AiralogyDev123!" } })
    expect(signin.ok()).toBeTruthy()
    const headers = { "Auth-Token": (await signin.json()).token }
    async function get(path: string) {
      const response = await request.get(`${api}${path}`, { headers })
      expect(response.ok(), await response.text()).toBeTruthy()
      return response.json()
    }
    async function post(path: string, data: unknown) {
      const response = await request.post(`${api}${path}`, { headers, data })
      expect(response.ok(), await response.text()).toBeTruthy()
      return response.json()
    }
    await page.addInitScript(language => localStorage.setItem("lang", JSON.stringify({ data: language, expire: null })), locale)
    const projectPath = `/labs/${fixtures.lab.uid}/projects/${fixtures.project.uid}`
    const loadedContext = page.waitForResponse(response => response.url().includes("/workflow-definitions/context?") && response.ok())
    await page.goto(`${projectPath}/workflows`)
    const context: WorkflowContext = await (await loadedContext).json()
    expect(context.capabilities).toMatchObject({ read: true, write: true, run: true })
    const protocol = context.protocols.find(protocol => protocol.id === fixtures.analysis.protocol_id)!
    expect(protocol).toBeTruthy()
    await expect(page.getByTestId("workflow-workbench")).toBeVisible()
    await expect(page.getByRole("heading", { name: locale === "en-US" ? "Workflows" : "工作流", exact: true })).toBeVisible()
    const title = `Synthetic Workflow ${locale} ${randomUUID().slice(0, 8)}`
    await page.getByTestId("workflow-title").locator("input").fill(title)
    await page.getByTestId("workflow-add-protocol").click()
    await selectVisibleOption(page, protocol.name)
    await page.getByTestId("workflow-add-card").click()
    await page.getByTestId("workflow-card-title").locator("input").fill("Measure A")
    await page.getByTestId("workflow-view-list").click()
    const firstId = await page.getByTestId("workflow-card-list").locator("article").first().getAttribute("data-node-id")
    await page.getByTestId("workflow-duplicate-card").click()
    await page.getByTestId("workflow-card-title").locator("input").fill("Measure B")
    const cards = page.getByTestId("workflow-card-list").locator("article")
    await expect(cards).toHaveCount(2)
    const secondId = await cards.last().getAttribute("data-node-id")
    expect(secondId).not.toBe(firstId)
    await page.getByTestId("workflow-card-dependencies").click()
    await selectVisibleOption(page, "1. Measure A")
    await page.keyboard.press("Escape")
    await cards.last().getByRole("button", { name: locale === "en-US" ? "Move up" : "上移", exact: true }).click()
    expect(await cards.first().getAttribute("data-node-id")).toBe(secondId)
    await expect(cards.first()).toContainText("Measure A")

    const previewResponse = page.waitForResponse(response => response.url().endsWith("/workflow-definitions/preview") && response.request().method() === "POST")
    await page.getByTestId("workflow-preview-save").click()
    const preview: WorkflowSavePreview = await (await previewResponse).json()
    expect(preview.graph.nodes.map(node => node.node_id)).toEqual([secondId, firstId])
    expect(preview.graph.edges).toMatchObject([{ source_node_id: firstId, target_node_id: secondId, condition: null }])
    expect(preview.pins).toHaveLength(2)
    expect(preview.pins.every(pin => pin.protocol_id === protocol.id && pin.protocol_version_id === protocol.versions[0].id)).toBe(true)
    await page.setViewportSize({ width: 390, height: 844 })
    const saveDialog = page.locator(".n-modal").filter({ has: page.getByTestId("workflow-confirm-save") })
    await expect(saveDialog).toBeVisible()
    await expect(saveDialog).toHaveCSS("opacity", "1")
    await expect.poll(async () => (await saveDialog.boundingBox())?.width).toBeLessThanOrEqual(358)
    const box = (await saveDialog.boundingBox())!
    expect(box.x).toBeGreaterThanOrEqual(15)
    expect(box.x + box.width).toBeLessThanOrEqual(375)
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    const confirmation = page.waitForResponse(response => response.url().endsWith("/workflow-definitions/confirm") && response.request().method() === "POST")
    await page.getByTestId("workflow-confirm-save").click()
    const saved: WorkflowDefinitionDetail = await (await confirmation).json()
    expect(saved.revision).toBe(1)
    const firstRevision = saved.current_revision!.id
    await expect(saveDialog).toBeHidden()
    await expect(page.getByTestId("workflow-result")).toContainText(title)
    await expect(page.getByTestId("workflow-card-list")).toBeVisible()
    await expect(page.getByTestId("workflow-canvas")).toHaveCount(0)
    await page.reload()
    await page.getByTestId("workflow-saved-item").filter({ hasText: title }).click()
    await expect(cards).toHaveCount(2)
    expect(await cards.first().getAttribute("data-node-id")).toBe(secondId)
    await page.getByTestId("workflow-title").locator("input").fill(`${title} revised`)
    await page.getByTestId("workflow-preview-save").click()
    const revisionConfirmation = page.waitForResponse(response => response.url().endsWith("/workflow-definitions/confirm") && response.request().method() === "POST")
    await page.getByTestId("workflow-confirm-save").click()
    const revised: WorkflowDefinitionDetail = await (await revisionConfirmation).json()
    expect(revised.revision).toBe(2)
    expect(revised.current_revision!.id).not.toBe(firstRevision)
    const history: WorkflowDefinitionDetail = await get(`/workflow-definitions/${saved.id}`)
    expect(history.revisions.find(revision => revision.id === firstRevision)?.title).toBe(title)
    await expect(saveDialog).toBeHidden()
    await page.getByTestId("workflow-revision").click()
    await selectVisibleOption(page, locale === "en-US" ? "Revision 1" : "修订 1")
    await expect(page.getByTestId("workflow-title").locator("input")).toHaveValue(title)
    await expect(page.getByTestId("workflow-preview-save")).toBeDisabled()

    const taskDraft = { project_id: fixtures.project.id, title: `Synthetic Workflow run ${locale} ${randomUUID().slice(0, 8)}`, goal: "Collect two separate synthetic measurement Records in order", success_criteria: ["Both fixed Protocol cards have independent submitted Records"], protocol_ids: [protocol.id] }
    const taskPreview = await post("/research-tasks/preview", taskDraft)
    const task = await post("/research-tasks", { ...taskDraft, preview_digest: taskPreview.preview_digest })
    if (process.env.AI_ENABLED === "false")
      expect(task.ai_available).toBe(false)
    await page.getByTestId("workflow-open-run").click()
    await page.getByTestId("workflow-task").click()
    await selectVisibleOption(page, taskDraft.title)
    const runPreviewResponse = page.waitForResponse(response => response.url().endsWith(`/workflow-definitions/${saved.id}/runs/preview`) && response.request().method() === "POST")
    await page.getByTestId("workflow-preview-run").click()
    const runPreview: WorkflowRunPreview = await (await runPreviewResponse).json()
    expect(runPreview.workflow_revision_id).toBe(firstRevision)
    expect(runPreview.task_id).toBe(task.id)
    expect(runPreview.pins).toHaveLength(2)
    await expect(page.getByTestId("workflow-run-contract")).toContainText(locale === "en-US" ? "Budget limit" : "预算上限")
    await page.getByTestId("workflow-run-environment").locator("summary").click()
    await expect(page.getByTestId("workflow-run-environment").locator("pre")).toContainText("executor_bindings")
    await expect(page.getByTestId("workflow-run-environment").locator("pre")).toContainText(protocol.versions[0].id)
    const runConfirmation = page.waitForResponse(response => response.url().endsWith(`/workflow-definitions/${saved.id}/runs/confirm`) && response.request().method() === "POST")
    await page.getByTestId("workflow-confirm-run").click()
    const receipt = await (await runConfirmation).json()
    expect(receipt.actions).toHaveLength(2)
    expect(new Set(receipt.actions.map((action: { id: string }) => action.id)).size).toBe(2)
    expect(receipt.actions.find((action: { node_id: string }) => action.node_id === secondId)?.status).toBe("blocked")
    await expect(page).toHaveURL(new RegExp(`/research/tasks/${task.id}$`))
    await expect(page.getByTestId("research-current-status")).toBeVisible()
    const replay = await post(`/workflow-definitions/${saved.id}/runs/confirm`, (await runConfirmation).request().postDataJSON())
    expect(replay.run_id).toBe(receipt.run_id)
    expect(replay.actions.map((action: { id: string }) => action.id)).toEqual(receipt.actions.map((action: { id: string }) => action.id))
    await page.goto(`${projectPath}/workflows`)
    await page.getByTestId("workflow-saved-item").filter({ hasText: title }).click()
    await expect(page.getByRole("button", { name: locale === "en-US" ? "Open Research Task" : "打开科研任务", exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    const workbench = page.getByTestId("workflow-workbench")
    await workbench.scrollIntoViewIfNeeded()
    await expect.poll(() => workbench.evaluate((element) => {
      let current: Element | null = element
      while (current) {
        if (getComputedStyle(current).opacity !== "1")
          return false
        current = current.parentElement
      }
      return true
    })).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`workflow-${locale}-phone.png`), fullPage: true })
  })
}

for (const locale of ["en-US", "zh-CN"] as const) {
  test(`Published Analysis card uses newly submitted Records and supplies a reviewed downstream input (${locale})`, async ({ page, request }, testInfo) => {
    test.setTimeout(180_000)
    const fixtures = await loadFixtures()
    const api = process.env.E2E_API_URL || "http://127.0.0.1:4100"
    const signin = await request.post(`${api}/signin_by_email`, { data: { email: "dev.owner@airalogy.dev", password: "AiralogyDev123!" } })
    expect(signin.ok()).toBeTruthy()
    const headers = { "Auth-Token": (await signin.json()).token }
    async function call(path: string, data?: unknown) {
      const response = await request.fetch(`${api}${path}`, { method: data === undefined ? "GET" : "POST", headers, data })
      expect(response.ok(), `${path}: ${await response.text()}`).toBeTruthy()
      return response.json()
    }
    const records = (await call(`/protocols/${fixtures.analysis.protocol_id}/records?page_size=20`)).records
    const historical = records.slice(0, 2)
    const fresh = records[2]
    const privateMean = historical.reduce((sum: number, record: { data: { var: { measurement: number } } }) => sum + record.data.var.measurement, 0) / 2
    expect(fresh.data.var.measurement).not.toBe(privateMean)
    const privatePreview = await call("/analyses/preview", {
      protocol_id: fixtures.analysis.protocol_id,
      selection: { mode: "selected", filters: {}, records: historical.map((record: { record_id: string, record_version: number }) => ({ id: record.record_id, version: record.record_version })) },
      recipe: { schema_version: 1, numeric_fields: ["measurement"], group_by: [], filters: [], missing_policy: "exclude", chart: "bar" },
      question: "Synthetic private analysis used only to save a reusable recipe",
    })
    const privateRun = await call("/analyses", { preview_id: privatePreview.id, preview_digest: privatePreview.preview_digest, client_idempotency_key: randomUUID() })
    await expect.poll(async () => (await call(`/analyses/${privateRun.id}`)).status).toBe("succeeded")
    const title = `Synthetic published analysis ${locale} ${randomUUID().slice(0, 8)}`
    const privateMethod = await call("/analysis-pipelines", { run_id: privateRun.id, title })
    const listPublications = () => call(`/workflow-analysis-methods?project_id=${fixtures.project.id}`)
    expect((await listPublications()).items.some((item: { title: string }) => item.title === title)).toBe(false)
    await page.addInitScript(language => localStorage.setItem("lang", JSON.stringify({ data: language, expire: null })), locale)
    const projectPath = `/labs/${fixtures.lab.uid}/projects/${fixtures.project.uid}`
    const loadedContext = page.waitForResponse(response => response.url().includes("/workflow-definitions/context?") && response.ok())
    await page.goto(`${projectPath}/workflows`)
    const context: WorkflowContext = await (await loadedContext).json()
    const protocol = context.protocols.find(protocol => protocol.id === fixtures.analysis.protocol_id)!
    await page.getByTestId("workflow-title").locator("input").fill(title)
    await page.getByTestId("workflow-add-protocol").click()
    await selectVisibleOption(page, protocol.name)
    await page.getByTestId("workflow-add-card").click()
    await page.getByTestId("workflow-card-title").locator("input").fill("Submitted measurement")
    await page.getByTestId("workflow-view-list").click()
    const cards = page.getByTestId("workflow-card-list").locator("article")
    const sourceId = (await cards.first().getAttribute("data-node-id"))!
    await page.getByTestId("workflow-card-kind").locator('input[value="analysis"]').check()
    await page.getByTestId("workflow-publish-method").click()
    await page.getByTestId("analysis-method-private-select").click()
    await selectVisibleOption(page, title)
    const publicationPreviewResponse = page.waitForResponse(response => response.url().endsWith("/workflow-analysis-methods/preview") && response.request().method() === "POST")
    await page.getByTestId("analysis-method-preview-publication").click()
    const publicationPreview: WorkflowAnalysisPublicationPreview = await (await publicationPreviewResponse).json()
    expect(publicationPreview.excluded_fields).toEqual(["source_selection", "source_records", "results", "ai_provenance"])
    expect(publicationPreview.publication.recipe).toMatchObject({ numeric_fields: ["measurement"] })
    expect((await listPublications()).items.some((item: { title: string }) => item.title === title)).toBe(false)
    await expect(page.getByTestId("analysis-method-confirm-publication")).toBeDisabled()
    await page.setViewportSize({ width: 390, height: 844 })
    const publicationDialog = page.getByTestId("analysis-method-publish-dialog")
    await expect.poll(async () => (await publicationDialog.boundingBox())?.width).toBeLessThanOrEqual(358)
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`workflow-method-publication-${locale}-phone.png`) })
    await page.getByTestId("analysis-method-publish-reviewed").click()
    const publicationResponse = page.waitForResponse(response => response.url().endsWith("/workflow-analysis-methods/confirm") && response.request().method() === "POST")
    await page.getByTestId("analysis-method-confirm-publication").click()
    const publication: WorkflowAnalysisPublication = await (await publicationResponse).json()
    expect(publication.id).toBeTruthy()
    expect(publication).not.toHaveProperty("pipeline_revision_id")
    expect(publication).not.toHaveProperty("source_selection")
    await expect(page.getByTestId("analysis-method-published")).toContainText(title)
    await publicationDialog.getByRole("button", { name: locale === "en-US" ? "Close" : "关闭", exact: true }).click()
    await expect(cards).toHaveCount(1)
    expect((await call(`/analysis-pipelines/${privateMethod.id}`)).id).toBe(privateMethod.id)
    expect((await call(`/analyses/${privateRun.id}`)).result.groups[0].fields.measurement.mean).toBe(privateMean)
    await page.getByTestId("workflow-add-analysis-card").click()
    await page.getByTestId("workflow-card-title").locator("input").fill("Analyze submitted measurement")
    const analysisId = (await cards.last().getAttribute("data-node-id"))!
    await page.getByTestId("workflow-card-dependencies").click()
    await selectVisibleOption(page, "1. Submitted measurement")
    await page.keyboard.press("Escape")
    await page.getByTestId("workflow-analysis-sources").click()
    await selectVisibleOption(page, "Submitted measurement")
    await page.keyboard.press("Escape")
    await page.getByTestId("workflow-analysis-output-id").locator("input").fill("mean_measurement")
    await page.getByTestId("workflow-analysis-output-field").click()
    await selectVisibleOption(page, "Measurement")
    const outputResponse = page.waitForResponse(response => response.url().endsWith(`/workflow-analysis-methods/${publication.id}/outputs/preview`) && response.request().method() === "POST" && response.request().postDataJSON().outputs.length === 1)
    await page.getByTestId("workflow-analysis-add-output").click()
    const outputCatalog = await (await outputResponse).json()
    expect(outputCatalog.fields[0]).toMatchObject({ path: ["analysis", "mean_measurement"], value_type: "number", unit: "mg/L" })
    await page.getByTestId("workflow-card-kind").locator('input[value="protocol"]').check()
    await page.getByTestId("workflow-add-card").click()
    await page.getByTestId("workflow-card-title").locator("input").fill("Use analyzed measurement")
    const targetId = (await cards.last().getAttribute("data-node-id"))!
    await page.getByTestId("workflow-card-dependencies").click()
    await selectVisibleOption(page, "2. Analyze submitted measurement")
    await page.keyboard.press("Escape")
    await page.getByTestId("workflow-binding-source-card").click()
    await selectVisibleOption(page, "Analyze submitted measurement")
    await page.getByTestId("workflow-binding-source-field").click()
    await selectVisibleOption(page, `${outputCatalog.fields[0].title} (mg/L)`)
    await page.getByTestId("workflow-binding-target-field").click()
    await selectVisibleOption(page, "Measurement (mg/L)")
    await page.getByTestId("workflow-binding-add").click()
    const savePreviewResponse = page.waitForResponse(response => response.url().endsWith("/workflow-definitions/preview") && response.request().method() === "POST")
    await page.getByTestId("workflow-preview-save").click()
    const preview: WorkflowSavePreview = await (await savePreviewResponse).json()
    expect(preview.graph.schema_version).toBe(2)
    expect(preview.graph.nodes.find(node => node.node_id === analysisId)).toMatchObject({ kind: "analysis", method_publication_id: publication.id, record_sources: [{ source_node_id: sourceId, cardinality: "one" }], input_policy: "all_declared" })
    expect(preview.graph.bindings[0]).toMatchObject({ source_path: ["analysis", "mean_measurement"], target_path: ["var", "measurement"] })
    expect(JSON.stringify(preview.graph)).not.toContain(privateMethod.id)
    for (const record of historical)
      expect(JSON.stringify(preview.graph)).not.toContain(record.record_id)
    const saveResponse = page.waitForResponse(response => response.url().endsWith("/workflow-definitions/confirm") && response.request().method() === "POST")
    await page.getByTestId("workflow-confirm-save").click()
    const saved: WorkflowDefinitionDetail = await (await saveResponse).json()
    await page.reload()
    await page.getByTestId("workflow-saved-item").filter({ hasText: title }).click()
    await expect(cards).toHaveCount(3)
    expect((await call(`/workflow-definitions/${saved.id}`)).current_revision.graph).toEqual(preview.graph)
    const taskDraft = { project_id: fixtures.project.id, title: `${title} run`, goal: "Analyze only explicitly submitted synthetic Records and reuse the reviewed result", success_criteria: ["The new source determines the mean and downstream input"], protocol_ids: [protocol.id] }
    const taskPreview = await call("/research-tasks/preview", taskDraft)
    const task = await call("/research-tasks", { ...taskDraft, preview_digest: taskPreview.preview_digest })
    await page.getByTestId("workflow-open-run").click()
    await page.getByTestId("workflow-task").click()
    await selectVisibleOption(page, taskDraft.title)
    const runPreviewResponse = page.waitForResponse(response => response.url().endsWith(`/workflow-definitions/${saved.id}/runs/preview`) && response.request().method() === "POST")
    await page.getByTestId("workflow-preview-run").click()
    const runPreview: WorkflowRunPreview = await (await runPreviewResponse).json()
    expect(runPreview.pins.find(pin => pin.node_id === analysisId)).toMatchObject({ kind: "analysis", method_publication_id: publication.id, content_digest: publication.digest })
    await expect(page.getByTestId("workflow-data-summary")).toContainText(publication.digest)
    await page.getByTestId("workflow-confirm-run").click()
    await expect(page).toHaveURL(new RegExp(`/research/tasks/${task.id}$`))
    async function readAction(nodeId: string): Promise<ResearchAction> {
      return (await call(`/research-tasks/${task.id}`)).actions.find((action: ResearchAction) => action.input_data.action_graph?.node_id === nodeId)
    }
    async function approve(action: ResearchAction) {
      const card = page.locator("#research-approvals article").filter({ has: page.getByRole("heading", { name: action.title, exact: true }) })
      await card.getByRole("button", { name: locale === "en-US" ? "Approve Action" : "批准 Action", exact: true }).click()
      const response = page.waitForResponse(response => response.url().endsWith(`/research-approvals/${action.approval!.id}/approve`) && response.request().method() === "POST")
      await page.getByRole("button", { name: locale === "en-US" ? "Confirm approval" : "确认批准", exact: true }).click()
      expect((await response).ok()).toBe(true)
    }
    await approve(await readAction(sourceId))
    const sourceWork = (await readAction(sourceId)).work_item!
    await call(`/research-work-items/${sourceWork.id}/submit`, { expected_revision: sourceWork.revision, record_id: fresh.record_id, record_version: fresh.record_version, note: "Synthetic fixture submission only; no physical experiment performed." })
    const analysis = await readAction(analysisId)
    expect(analysis.kind).toBe("analysis_run")
    expect(analysis.approval?.status).toBe("pending")
    expect(analysis.input_data.analysis_input.selection.records).toEqual([{ id: fresh.record_id, version: fresh.record_version }])
    expect(analysis.analysis_run?.method?.digest).toBe(publication.digest)
    await page.reload()
    const actualApproval = page.locator("#research-approvals article").filter({ has: page.getByRole("heading", { name: analysis.title, exact: true }) })
    await expect(actualApproval.getByTestId("workflow-analysis-method-contract")).toContainText("measurement")
    await expect(actualApproval.getByTestId("workflow-resolution-summary")).toContainText(fresh.record_id)
    await actualApproval.scrollIntoViewIfNeeded()
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`workflow-analysis-approval-${locale}-phone.png`) })
    await approve(analysis)
    await expect.poll(async () => (await readAction(analysisId)).status, { timeout: 30_000 }).toBe("completed")
    const completed = await readAction(analysisId)
    const result = completed.output_data.analysis_result
    expect(result.outputs).toEqual({ analysis: { mean_measurement: fresh.data.var.measurement } })
    expect(result.report.groups[0].fields.measurement).toMatchObject({ mean: fresh.data.var.measurement, count: 1 })
    expect(completed.analysis_run?.can_open_private_report).toBe(true)
    const downstream = await readAction(targetId)
    expect(downstream.approval?.status).toBe("pending")
    expect(downstream.input_data.initial_values).toEqual({ measurement: fresh.data.var.measurement })
    expect(downstream.input_data.workflow_resolution.receipt.sources[analysisId]).toMatchObject({ kind: "analysis", analysis_id: result.analysis_id, result_digest: result.result_digest })
    await page.reload()
    const downstreamApproval = page.locator("#research-approvals article").filter({ has: page.getByRole("heading", { name: downstream.title, exact: true }) })
    await expect(downstreamApproval.getByTestId("workflow-resolution-summary")).toContainText(result.analysis_id)
    await expect(page.getByTestId("workflow-analysis-result-ports")).toContainText(`"mean_measurement": ${fresh.data.var.measurement}`)
    await expect(page.getByTestId("workflow-analysis-open-report")).toBeVisible()
    await downstreamApproval.scrollIntoViewIfNeeded()
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`workflow-analysis-downstream-${locale}-phone.png`) })
    await approve(downstream)
    expect((await readAction(targetId)).protocol_run?.initial_values).toEqual({ measurement: fresh.data.var.measurement })
    await page.getByTestId("workflow-analysis-open-report").click()
    await expect(page).toHaveURL(new RegExp(`runId=${result.analysis_id}`))
    await expect(page.getByTestId("analysis-result-table")).toContainText(String(fresh.data.var.measurement))
  })
}

for (const locale of ["en-US", "zh-CN"] as const) {
  test(`Workflow conditions and scalar mappings resolve real Records and expose downstream approval (${locale})`, async ({ page, request }, testInfo) => {
    test.setTimeout(120_000)
    const fixtures = await loadFixtures()
    const api = process.env.E2E_API_URL || "http://127.0.0.1:4100"
    const signin = await request.post(`${api}/signin_by_email`, { data: { email: "dev.owner@airalogy.dev", password: "AiralogyDev123!" } })
    expect(signin.ok()).toBeTruthy()
    const headers = { "Auth-Token": (await signin.json()).token }
    async function call(path: string, data?: unknown) {
      const response = await request.fetch(`${api}${path}`, { method: data === undefined ? "GET" : "POST", headers, data })
      expect(response.ok(), `${path}: ${await response.text()}`).toBeTruthy()
      return response.json()
    }
    await page.addInitScript(language => localStorage.setItem("lang", JSON.stringify({ data: language, expire: null })), locale)
    const projectPath = `/labs/${fixtures.lab.uid}/projects/${fixtures.project.uid}`
    const loadedContext = page.waitForResponse(response => response.url().includes("/workflow-definitions/context?") && response.ok())
    await page.goto(`${projectPath}/workflows`)
    const context: WorkflowContext = await (await loadedContext).json()
    const protocol = context.protocols.find(protocol => protocol.id === fixtures.analysis.protocol_id)!
    const field = protocol.versions[0].fields!.find(field => field.path[1] === "measurement")!
    expect(field).toMatchObject({ path: ["var", "measurement"], value_type: "number", unit: "mg/L" })
    const title = `Synthetic conditional Workflow ${locale} ${randomUUID().slice(0, 8)}`
    await page.getByTestId("workflow-title").locator("input").fill(title)
    await page.getByTestId("workflow-add-protocol").click()
    await selectVisibleOption(page, protocol.name)
    await page.getByTestId("workflow-add-card").click()
    await page.getByTestId("workflow-card-title").locator("input").fill("Source measurement")
    await page.getByTestId("workflow-view-list").click()
    const cards = page.getByTestId("workflow-card-list").locator("article")
    const sourceId = (await cards.first().getAttribute("data-node-id"))!
    await page.getByTestId("workflow-duplicate-card").click()
    await page.getByTestId("workflow-card-title").locator("input").fill("Bound measurement")
    const targetId = (await cards.last().getAttribute("data-node-id"))!
    async function setCondition(operator: "gte" | "lt") {
      await page.getByTestId("workflow-card-dependencies").click()
      await selectVisibleOption(page, "1. Source measurement")
      await page.keyboard.press("Escape")
      await page.getByTestId("workflow-condition-mode").click()
      await selectVisibleOption(page, locale === "en-US" ? "Only when a field condition is met" : "仅当字段满足条件")
      await page.getByTestId("workflow-condition-field").click()
      await selectVisibleOption(page, `${field.title} (mg/L)`)
      await page.getByTestId("workflow-condition-operator").click()
      await selectVisibleOption(page, operator === "gte" ? locale === "en-US" ? "At least (≥)" : "大于等于（≥）" : locale === "en-US" ? "Less than (<)" : "小于（<）")
      await page.getByTestId("workflow-condition-value").locator("input").fill("0")
    }
    await setCondition("gte")
    await page.getByTestId("workflow-condition-value").locator("input").fill("not a number")
    await expect(page.getByTestId("workflow-graph-warning")).toBeVisible()
    await expect(page.getByTestId("workflow-preview-save")).toBeDisabled()
    await page.getByTestId("workflow-condition-value").locator("input").fill("0")
    await page.getByTestId("workflow-binding-source-card").click()
    await selectVisibleOption(page, "Source measurement")
    await page.getByTestId("workflow-binding-source-field").click()
    await selectVisibleOption(page, `${field.title} (mg/L)`)
    await page.getByTestId("workflow-binding-target-field").click()
    await selectVisibleOption(page, `${field.title} (mg/L)`)
    await page.getByTestId("workflow-binding-add").click()
    await expect(page.getByTestId("workflow-binding-item")).toContainText("mg/L")
    await page.getByTestId("workflow-duplicate-card").last().click()
    await page.getByTestId("workflow-card-title").locator("input").fill("Unselected branch")
    const skippedId = (await cards.last().getAttribute("data-node-id"))!
    await setCondition("lt")
    await expect(page.getByTestId("workflow-binding-item")).toHaveCount(0)
    const previewResponse = page.waitForResponse(response => response.url().endsWith("/workflow-definitions/preview") && response.request().method() === "POST")
    await page.getByTestId("workflow-preview-save").click()
    const preview: WorkflowSavePreview = await (await previewResponse).json()
    expect(preview.graph.edges.find(edge => edge.target_node_id === targetId)?.condition).toMatchObject({ path: ["var", "measurement"], value_type: "number", operator: "gte", value: 0, unit: "mg/L" })
    expect(preview.graph.edges.find(edge => edge.target_node_id === skippedId)?.condition).toMatchObject({ operator: "lt", value: 0 })
    expect(preview.graph.bindings).toMatchObject([{ source_node_id: sourceId, source_path: ["var", "measurement"], target_node_id: targetId, target_path: ["var", "measurement"], value_type: "number", unit: "mg/L", cardinality: "one" }])
    const saveDialog = page.locator(".n-modal").filter({ has: page.getByTestId("workflow-confirm-save") })
    await expect(saveDialog.getByTestId("workflow-data-summary")).toContainText("mg/L")
    await expect(saveDialog.getByTestId("workflow-data-summary")).toContainText("≥ 0")
    const savedResponse = page.waitForResponse(response => response.url().endsWith("/workflow-definitions/confirm") && response.request().method() === "POST")
    await page.getByTestId("workflow-confirm-save").click()
    const saved: WorkflowDefinitionDetail = await (await savedResponse).json()
    await expect(saveDialog).toBeHidden()
    await page.reload()
    await page.getByTestId("workflow-saved-item").filter({ hasText: title }).click()
    await page.getByTestId("workflow-view-list").click()
    await cards.filter({ hasText: "Bound measurement" }).getByRole("button", { name: locale === "en-US" ? "Configure card" : "配置卡片", exact: true }).click()
    await expect(page.getByTestId("workflow-binding-item")).toContainText("mg/L")
    await expect(page.getByTestId("workflow-condition-value").locator("input")).toHaveValue("0")

    const taskDraft = { project_id: fixtures.project.id, title: `Synthetic branch run ${locale} ${randomUUID().slice(0, 8)}`, goal: "Validate conditional Record routing and explicit scalar mapping using seeded synthetic Records", success_criteria: ["A false branch is skipped and the bound input requires a new approval"], protocol_ids: [protocol.id] }
    const taskPreview = await call("/research-tasks/preview", taskDraft)
    const task = await call("/research-tasks", { ...taskDraft, preview_digest: taskPreview.preview_digest })
    await page.getByTestId("workflow-open-run").click()
    await page.getByTestId("workflow-task").click()
    await selectVisibleOption(page, taskDraft.title)
    const runPreviewResponse = page.waitForResponse(response => response.url().endsWith(`/workflow-definitions/${saved.id}/runs/preview`) && response.request().method() === "POST")
    await page.getByTestId("workflow-preview-run").click()
    const runPreview: WorkflowRunPreview = await (await runPreviewResponse).json()
    expect(runPreview.edges).toEqual(preview.graph.edges)
    expect(runPreview.bindings).toEqual(preview.graph.bindings)
    const runDialog = page.locator(".n-modal").filter({ has: page.getByTestId("workflow-confirm-run") })
    await expect(runDialog.getByTestId("workflow-data-summary")).toContainText(locale === "en-US" ? "reviewed again" : "仍须重新核对")
    await page.getByTestId("workflow-confirm-run").click()
    await expect(page).toHaveURL(new RegExp(`/research/tasks/${task.id}$`))
    const taskBefore: ResearchTaskDetail = await call(`/research-tasks/${task.id}`)
    const sourceAction = taskBefore.actions.find(action => action.input_data.action_graph?.node_id === sourceId)!
    expect(sourceAction.approval?.status).toBe("pending")
    const sourceApprovalCard = page.locator("#research-approvals article").filter({ has: page.getByRole("heading", { name: "Source measurement", exact: true }) })
    await sourceApprovalCard.getByRole("button", { name: locale === "en-US" ? "Approve Action" : "批准 Action", exact: true }).click()
    const approvedResponse = page.waitForResponse(response => response.url().endsWith(`/research-approvals/${sourceAction.approval!.id}/approve`) && response.request().method() === "POST")
    await page.getByRole("button", { name: locale === "en-US" ? "Confirm approval" : "确认批准", exact: true }).click()
    expect((await approvedResponse).ok()).toBe(true)
    const afterApproval: ResearchTaskDetail = await call(`/research-tasks/${task.id}`)
    const sourceWork = afterApproval.actions.find(action => action.id === sourceAction.id)!.work_item!
    const records = await call(`/protocols/${protocol.id}/records?page_size=20`)
    const sourceRecord = records.records[0]
    expect(sourceRecord.data.var.measurement).toBeGreaterThan(0)
    await call(`/research-work-items/${sourceWork.id}/submit`, { expected_revision: sourceWork.revision, record_id: sourceRecord.record_id, record_version: sourceRecord.record_version, note: "Synthetic seeded Record submitted to verify Workflow routing; no physical experiment performed." })
    const resolved: ResearchTaskDetail = await call(`/research-tasks/${task.id}`)
    const byNode = (id: string) => resolved.actions.find(action => action.input_data.action_graph?.node_id === id) as ResearchAction
    const bound = byNode(targetId)
    expect(bound.input_data.initial_values).toEqual({ measurement: sourceRecord.data.var.measurement })
    expect(bound.input_data.workflow_resolution).toMatchObject({ state: "ready", receipt: { sources: { [sourceId]: { record_id: sourceRecord.record_id, record_version: sourceRecord.record_version } } } })
    expect(bound.approval?.status).toBe("pending")
    expect(bound.requirements.workflow_bound_input_confirmation).toBe(true)
    expect(byNode(skippedId)).toMatchObject({ status: "skipped", error: null, input_data: { workflow_resolution: { state: "branch_not_selected" } } })
    await page.reload()
    const boundApproval = page.locator("#research-approvals article").filter({ has: page.getByRole("heading", { name: "Bound measurement", exact: true }) })
    await expect(boundApproval.getByTestId("workflow-resolution-summary")).toContainText(sourceRecord.record_id)
    await expect(boundApproval.getByTestId("workflow-resolution-summary")).toContainText("Source measurement")
    await expect(boundApproval.getByTestId("workflow-resolution-summary")).toContainText("mg/L")
    await expect(boundApproval.locator("pre")).toContainText(`"measurement": ${sourceRecord.data.var.measurement}`)
    await page.setViewportSize({ width: 390, height: 844 })
    await boundApproval.scrollIntoViewIfNeeded()
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`workflow-resolved-approval-${locale}-phone.png`) })
    await boundApproval.getByRole("button", { name: locale === "en-US" ? "Approve Action" : "批准 Action", exact: true }).click()
    const boundApprovalResponse = page.waitForResponse(response => response.url().endsWith(`/research-approvals/${bound.approval!.id}/approve`) && response.request().method() === "POST")
    await page.getByRole("button", { name: locale === "en-US" ? "Confirm approval" : "确认批准", exact: true }).click()
    const boundResponse = await boundApprovalResponse
    expect(boundResponse.ok()).toBe(true)
    expect(boundResponse.request().postDataJSON().preview_digest).toBe(bound.approval!.preview_digest)
    const afterBoundApproval: ResearchTaskDetail = await call(`/research-tasks/${task.id}`)
    const approvedBound = afterBoundApproval.actions.find(action => action.id === bound.id)!
    expect(approvedBound.approval?.status).toBe("approved")
    expect(approvedBound.protocol_run?.initial_values).toEqual({ measurement: sourceRecord.data.var.measurement })
    expect(approvedBound.input_data.workflow_resolution.digest).toBe(bound.input_data.workflow_resolution.digest)
    await page.goto(`${projectPath}/workflows`)
    await page.getByTestId("workflow-saved-item").filter({ hasText: title }).click()
    await expect(page.locator("[data-skip-reason=\"branch_not_selected\"]")).toContainText(locale === "en-US" ? "Skipped: branch not selected" : "已跳过：未选择此分支")
    expect((await call(`/workflow-definitions/${saved.id}`)).runs[0].status).not.toBe("failed")
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`workflow-conditional-${locale}-phone.png`), fullPage: true })
  })
}
