import type { ResearchComputeEnvironment } from "../../../apps/web/src/service/api/research-compute"
import type { ResearchTaskDetail, ResearchTaskPreview } from "../../../apps/web/src/service/api/research-tasks"
import type { WorkflowAnalysisPublication, WorkflowAnalysisPublicationPreview } from "../../../apps/web/src/service/api/workflow-analysis-methods"
import type { WorkflowContext, WorkflowDefinitionDetail, WorkflowFileField, WorkflowRunPreview, WorkflowSavePreview } from "../../../apps/web/src/service/api/workflow-definitions"
import { randomUUID } from "node:crypto"
import { expect, test } from "@playwright/test"
import { loadFixtures, selectVisibleOption } from "./fixtures"

// Real disposable API/DB, including explicit publication, output catalog and Task
// previews. The saved method and offline environment are labelled synthetic UI
// fixtures, not an executed analysis. Real Runner execution is tested in PostgreSQL.
for (const locale of ["en-US", "zh-CN"] as const) {
  test(`Saved Compute method requires explicit publication, typed ports and exact governed environment (${locale})`, async ({ page, request }, testInfo) => {
    test.setTimeout(180_000)
    const fixtures = await loadFixtures()
    const seed = fixtures.workflow_compute
    const api = process.env.E2E_API_URL || "http://127.0.0.1:4100"
    const signIn = await request.post(`${api}/signin_by_email`, { data: { email: "dev.owner@airalogy.dev", password: "AiralogyDev123!" } })
    expect(signIn.ok()).toBe(true)
    const headers = { "Auth-Token": (await signIn.json()).token }
    async function get(path: string) {
      const response = await request.get(`${api}${path}`, { headers })
      expect(response.ok(), await response.text()).toBe(true)
      return response.json()
    }
    const title = `Synthetic Compute publication ${locale} ${randomUUID().slice(0, 8)}`
    const schema = { type: "object", properties: { mean: { title: "Synthetic mean", type: "number", unit: "mg/L" } }, required: ["mean"], additionalProperties: false }
    await page.addInitScript(language => localStorage.setItem("lang", JSON.stringify({ data: language, expire: null })), locale)
    const projectPath = `/labs/${fixtures.lab.uid}/projects/${fixtures.project.uid}`
    const contextResponse = page.waitForResponse(response => response.url().includes("/workflow-definitions/context?") && response.ok())
    await page.goto(`${projectPath}/workflows`)
    const context: WorkflowContext = await (await contextResponse).json()
    const protocol = context.protocols.find(protocol => protocol.id === seed.protocol_id)!
    const fileProtocol = context.protocols.find(protocol => protocol.id === fixtures.workflow_files.protocol_id)!
    const targetFileField = fileProtocol.versions.find(version => version.id === fixtures.workflow_files.protocol_version_id)!.fields!.find(field => field.value_type === "file" && field.path[1] === fixtures.workflow_files.field) as WorkflowFileField
    expect(targetFileField).toBeTruthy()
    expect(protocol).toBeTruthy()
    await page.getByTestId("workflow-title").locator("input").fill(title)
    await page.getByTestId("workflow-add-protocol").click()
    await selectVisibleOption(page, protocol.name)
    await page.getByTestId("workflow-add-card").click()
    await page.getByTestId("workflow-card-title").locator("input").fill("Submitted Compute input")
    await page.getByTestId("workflow-view-list").click()
    const cards = page.getByTestId("workflow-card-list").locator("article")
    const sourceId = (await cards.first().getAttribute("data-node-id"))!
    await page.getByTestId("workflow-card-kind").locator("input[value=\"analysis\"]").check()
    await page.getByTestId("workflow-publish-method").click()
    await page.getByTestId("analysis-method-private-select").click()
    await selectVisibleOption(page, seed.pipeline_title)
    await page.getByTestId("analysis-method-publish-title").locator("input").fill(title)
    await page.getByTestId("analysis-method-result-schema").locator("textarea").fill(JSON.stringify(schema, null, 2))
    const previewResponse = page.waitForResponse(response => response.url().endsWith("/workflow-analysis-methods/preview") && response.request().method() === "POST")
    await page.getByTestId("analysis-method-preview-publication").click()
    const previewHttp = await previewResponse
    expect(previewHttp.ok(), await previewHttp.text()).toBe(true)
    const preview: WorkflowAnalysisPublicationPreview = await previewHttp.json()
    expect(preview.publication.engine_version).toBe("airalogy.compute.analysis.v1")
    expect(preview.publication.compute_contract?.environment.source_revision_id).toBe(seed.environment_revision_id)
    expect(preview.publication.compute_contract?.result_schema).toEqual(schema)
    expect(preview.excluded_fields).toEqual(["source_selection", "source_records", "results", "ai_provenance", "original_approver", "original_budget", "original_deadline"])
    expect((await get(`/workflow-analysis-methods?project_id=${fixtures.project.id}`)).items.some((method: { title: string }) => method.title === title)).toBe(false)
    await expect(page.getByTestId("analysis-method-confirm-publication")).toBeDisabled()
    await page.setViewportSize({ width: 390, height: 844 })
    await expect(page.getByTestId("workflow-published-compute-code")).toContainText("statistics.mean")
    await expect(page.getByTestId("workflow-published-result-schema")).toContainText("mg/L")
    const publicationDialog = page.getByTestId("analysis-method-publish-dialog")
    await expect.poll(async () => (await publicationDialog.boundingBox())?.width).toBeLessThanOrEqual(358)
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    await page.getByTestId("workflow-published-compute-code").scrollIntoViewIfNeeded()
    await page.screenshot({ path: testInfo.outputPath(`workflow-compute-publication-${locale}-phone.png`) })
    await page.getByTestId("analysis-method-publish-reviewed").click()
    const publishedResponse = page.waitForResponse(response => response.url().endsWith("/workflow-analysis-methods/confirm") && response.request().method() === "POST")
    await page.getByTestId("analysis-method-confirm-publication").click()
    const publication: WorkflowAnalysisPublication = await (await publishedResponse).json()
    expect(publication.id).toBeTruthy()
    expect(publication).not.toHaveProperty("pipeline_revision_id")
    expect(publication).not.toHaveProperty("ai_provenance")
    expect((await get(`/analysis-pipelines/${seed.pipeline_id}`)).id).toBe(seed.pipeline_id)
    await publicationDialog.getByRole("button", { name: locale === "en-US" ? "Close" : "关闭", exact: true }).click()
    const catalogResponse = page.waitForResponse(response => response.url().endsWith(`/workflow-analysis-methods/${publication.id}/outputs/catalog`) && response.ok())
    await page.getByTestId("workflow-add-analysis-card").click()
    const catalog = await (await catalogResponse).json()
    expect(catalog).toMatchObject({ kind: "compute", fields: [{ path: ["mean"], value_type: "number", unit: "mg/L", nullable: false }] })
    await page.getByTestId("workflow-card-title").locator("input").fill("Compute submitted Records")
    const analysisId = (await cards.last().getAttribute("data-node-id"))!
    await page.getByTestId("workflow-card-dependencies").click()
    await selectVisibleOption(page, "1. Submitted Compute input")
    await page.keyboard.press("Escape")
    await page.getByTestId("workflow-analysis-sources").click()
    await selectVisibleOption(page, "Submitted Compute input")
    await page.keyboard.press("Escape")
    await page.getByTestId("workflow-compute-output-id").locator("input").fill("mean_measurement")
    await page.getByTestId("workflow-compute-output-path").click()
    await selectVisibleOption(page, "\"mean\"")
    await expect(page.getByTestId("workflow-compute-output-type")).toContainText("mg/L")
    const outputResponse = page.waitForResponse(response => response.url().endsWith(`/workflow-analysis-methods/${publication.id}/outputs/preview`) && response.request().postDataJSON()?.outputs?.length === 1)
    await page.getByTestId("workflow-compute-add-output").click()
    const outputCatalog = await (await outputResponse).json()
    expect(outputCatalog.fields[0]).toMatchObject({ path: ["analysis", "mean_measurement"], value_type: "number", unit: "mg/L", nullable: false })
    await page.getByTestId("workflow-file-output-id").locator("input").fill("summary_file")
    await page.getByTestId("workflow-file-output-mount").click()
    await selectVisibleOption(page, "summary.csv")
    await expect(page.getByTestId("workflow-file-output-contract")).toContainText(locale === "en-US" ? "Required" : "必需文件")
    await expect(page.getByTestId("workflow-file-output-contract")).not.toContainText(/scalar|标量/i)
    const fileOutputResponse = page.waitForResponse(response => response.url().endsWith(`/workflow-analysis-methods/${publication.id}/outputs/preview`) && response.request().postDataJSON()?.file_outputs?.length === 1)
    await page.getByTestId("workflow-file-output-add").click()
    const fileOutputs = await (await fileOutputResponse).json()
    const fileField = fileOutputs.fields.find((field: { value_type: string }) => field.value_type === "file")
    expect(fileField).toMatchObject({ path: ["analysis", "summary_file"], unit: null, file_extensions: ["csv"] })
    await page.getByTestId("workflow-compute-outputs").scrollIntoViewIfNeeded()
    await page.screenshot({ path: testInfo.outputPath(`workflow-compute-ports-${locale}-phone.png`) })
    await page.getByTestId("workflow-card-kind").locator("input[value=\"protocol\"]").check()
    await page.getByTestId("workflow-add-protocol").click()
    await selectVisibleOption(page, fileProtocol.name)
    await page.getByTestId("workflow-add-card").click()
    await page.getByTestId("workflow-card-title").locator("input").fill("Review generated CSV")
    await page.getByTestId("workflow-card-dependencies").click()
    await selectVisibleOption(page, "2. Compute submitted Records")
    await page.keyboard.press("Escape")
    await page.getByTestId("workflow-binding-source-card").click()
    await selectVisibleOption(page, "Compute submitted Records")
    await page.getByTestId("workflow-binding-source-field").click()
    await selectVisibleOption(page, `${fileField.title} (${fileField.file_extensions.join(", ")})`)
    await page.getByTestId("workflow-binding-target-field").click()
    await selectVisibleOption(page, `${targetFileField.title} (${targetFileField.file_extensions?.join(", ") || "*"})`)
    await page.getByTestId("workflow-binding-add").click()
    const savePreviewResponse = page.waitForResponse(response => response.url().endsWith("/workflow-definitions/preview") && response.request().method() === "POST")
    await page.getByTestId("workflow-preview-save").click()
    const savePreviewHttp = await savePreviewResponse
    expect(savePreviewHttp.ok(), await savePreviewHttp.text()).toBe(true)
    const savePreview: WorkflowSavePreview = await savePreviewHttp.json()
    expect(savePreview.graph.schema_version).toBe(4)
    expect(savePreview.graph.nodes.find(node => node.node_id === analysisId)).toMatchObject({ analysis_kind: "compute", method_publication_id: publication.id, record_sources: [{ source_node_id: sourceId, cardinality: "one" }], compute_outputs: [{ output_id: "mean_measurement", path: ["mean"], value_type: "number", unit: "mg/L", nullable: false }] })
    expect(savePreview.graph.nodes.find(node => node.node_id === analysisId)).toHaveProperty("compute_file_outputs", [{ output_id: "summary_file", mount_name: "summary.csv" }])
    expect(savePreview.graph.bindings[0]).toMatchObject({ source_path: ["analysis", "summary_file"], target_path: ["var", fixtures.workflow_files.field], value_type: "file", unit: null })
    await expect(page.getByTestId("workflow-file-binding-preview")).toBeVisible()
    expect(JSON.stringify(savePreview.graph)).not.toContain(seed.pipeline_id)
    expect(JSON.stringify(savePreview.graph)).not.toContain("source_code")
    const savedResponse = page.waitForResponse(response => response.url().endsWith("/workflow-definitions/confirm") && response.request().method() === "POST")
    await page.getByTestId("workflow-confirm-save").click()
    const saved: WorkflowDefinitionDetail = await (await savedResponse).json()
    await expect(page.getByTestId("workflow-result")).toContainText(title)

    // Create through the actual Task UI: select r1 even though r2 is latest.
    await page.goto(`${projectPath}/research`)
    const revisionsResponse = page.waitForResponse(response => response.url().includes("/research-tasks/compute-environment-revisions?") && response.ok())
    await page.getByRole("button", { name: locale === "en-US" ? "New Research Task" : "新建科研任务", exact: true }).first().click()
    const revisions: { items: ResearchComputeEnvironment[] } = await (await revisionsResponse).json()
    const environmentRevisions = revisions.items.filter(item => item.source_id === seed.environment_id)
    expect(environmentRevisions).toHaveLength(2)
    expect(environmentRevisions.some(item => item.metadata.environment_revision === 2)).toBe(true)
    const taskTitle = `${title} Task`
    await page.getByTestId("research-task-title").locator("input").fill(taskTitle)
    await page.getByTestId("research-task-goal").locator("textarea").fill("Review a synthetic Compute method without running a synthetic offline Runner")
    await page.getByTestId("research-task-success-criteria").locator("textarea").fill("Fixed environment, exact ports, sources and approver are visible before any execution")
    await page.getByTestId("research-task-limits").locator("summary").click()
    await page.getByTestId("research-task-budget").locator("input").fill("1")
    await page.getByTestId("research-task-environment").locator("summary").click()
    await page.getByTestId("research-task-protocols").click()
    await selectVisibleOption(page, protocol.name)
    await selectVisibleOption(page, fileProtocol.name)
    await page.keyboard.press("Escape")
    await page.getByTestId("research-task-compute-revisions").click()
    await selectVisibleOption(page, `${seed.environment_name} · r1`)
    await page.keyboard.press("Escape")
    const taskPreviewResponse = page.waitForResponse(response => response.url().endsWith("/research-tasks/preview") && response.request().method() === "POST")
    await page.getByRole("button", { name: locale === "en-US" ? "Preview Task" : "预览任务", exact: true }).click()
    const taskPreviewHttp = await taskPreviewResponse
    expect(taskPreviewHttp.ok(), await taskPreviewHttp.text()).toBe(true)
    expect(taskPreviewHttp.request().postDataJSON().compute_environment_revision_ids).toEqual([seed.environment_revision_id])
    const taskPreview: ResearchTaskPreview = await taskPreviewHttp.json()
    expect(taskPreview.compute).toMatchObject([{ source_revision_id: seed.environment_revision_id, metadata: { environment_revision: 1 } }])
    const taskResponse = page.waitForResponse(response => response.url().endsWith("/research-tasks") && response.request().method() === "POST")
    await page.getByRole("button", { name: locale === "en-US" ? "Confirm and create" : "确认并创建", exact: true }).click()
    const task: ResearchTaskDetail = await (await taskResponse).json()
    await expect(page).toHaveURL(new RegExp(`/research/tasks/${task.id}$`))
    await page.goto(`${projectPath}/workflows`)
    await page.getByTestId("workflow-saved-item").filter({ hasText: title }).click()
    await expect(cards).toHaveCount(3)
    expect((await get(`/workflow-definitions/${saved.id}`)).current_revision.graph).toEqual(savePreview.graph)
    await page.getByTestId("workflow-open-run").click()
    await page.getByTestId("workflow-task").click()
    await selectVisibleOption(page, taskTitle)
    const approver = context.compute_approvers!.find(user => user.id === task.owner_user_id)!
    expect(approver).toBeTruthy()
    await page.getByTestId(`workflow-compute-approver-${analysisId}`).click()
    await selectVisibleOption(page, approver.name || approver.username)
    const runResponse = page.waitForResponse(response => response.url().endsWith(`/workflow-definitions/${saved.id}/runs/preview`) && response.request().method() === "POST")
    await page.getByTestId("workflow-preview-run").click()
    const runHttp = await runResponse
    expect(runHttp.ok(), await runHttp.text()).toBe(true)
    const run: WorkflowRunPreview = await runHttp.json()
    expect(runHttp.request().postDataJSON().compute_approvers).toEqual({ [analysisId]: approver.id })
    expect(run.compute_governance?.[analysisId]).toMatchObject({ approver_user_id: approver.id, budget_currency: "USD", deadline_at: null })
    expect(Number(run.compute_governance?.[analysisId].max_cost)).toBe(1)
    expect(run.environment.compute).toMatchObject([{ source_revision_id: seed.environment_revision_id, metadata: { environment_revision: 1 } }])
    await expect(page.getByTestId("workflow-compute-governance")).toContainText(approver.name || approver.username)
    await expect(page.getByTestId("workflow-compute-governance")).toContainText("USD")
    await page.getByTestId("workflow-compute-governance").scrollIntoViewIfNeeded()
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`workflow-compute-governance-${locale}-phone.png`) })
    // Preview is not execution; no run confirmation or model/Runner call here.
    expect((await get(`/research-tasks/${task.id}`)).actions).toHaveLength(0)
  })
}
